apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-collection-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-collection-api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}-collection-api
    spec:
      initContainers:
        - name: check-db
          image: {{ .Values.services.initdb.image }}
          command:
            - sh
            - -c
            - until pg_isready -h keycloak-db-service; do echo waiting for database; sleep 10; done;
        - name: init-db
          image: {{ .Values.services.initdb.image }}
          env:
          - name: POSTGRES_DB
            value: {{ .Values.services.initdb.environment.POSTGRES_DB }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.services.initdb.environment.POSTGRES_PASSWORD }}
          - name: POSTGRES_HOST
            value: {{ .Values.services.initdb.environment.POSTGRES_HOST }}
          - name: POSTGRES_USER
            value: {{ .Values.services.initdb.environment.POSTGRES_USER }}
          - name: DINA_DB
            value: {{ .Values.services.collectionapi.environment.DINA_DB }}
          - name: MIGRATION_USER_collection
            value: {{ .Values.services.collectionapi.environment.spring.liquibase.user }}
          - name: MIGRATION_USER_PW_collection
            value: {{ .Values.services.collectionapi.environment.spring.liquibase.password }}
          - name: WEB_USER_collection
            value: {{ .Values.services.collectionapi.environment.spring.datasource.username }}
          - name: WEB_USER_PW_collection
            value: {{ .Values.services.collectionapi.environment.spring.datasource.password }}
          - name: PG_EXTENSION_collection
            value: {{ .Values.services.collectionapi.environment.PG_EXTENSION_collection }}
      containers:
        - name: collection-api
          image: {{ .Values.services.collectionapi.image }}
          imagePullPolicy: {{ .Values.services.keycloak.pullPolicy }}
          env:
            - name: KEYCLOAK_ENABLED
              value: {{ .Values.global.environment.keycloak.enabled | quote }}         
            - name: KEYCLOAK_AUTH-SERVER-URL
              value: {{ .Values.global.environment.keycloak.auth_server_url }}
            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.services.collectionapi.environment.spring.datasource.url }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.services.collectionapi.environment.spring.datasource.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.services.collectionapi.environment.spring.datasource.password }}
            - name: SPRING_LIQUIBASE_USER
              value: {{ .Values.services.collectionapi.environment.spring.liquibase.user }}
            - name: SPRING_LIQUIBASE_PASSWORD
              value: {{ .Values.services.collectionapi.environment.spring.liquibase.password }}
            - name: ACTUATOR_ALLOWEDIP
              value: {{ .Values.services.collectionapi.environment.actuator.allowedIP }}
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 650
            periodSeconds: 5
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: {{ .Values.services.collectionapi.resources.requests.memory }}
              cpu: {{ .Values.services.collectionapi.resources.requests.cpu }}            
            limits:
              memory: {{ .Values.services.collectionapi.resources.limits.memory }} 
              cpu: {{ .Values.services.collectionapi.resources.limits.cpu }}
status: {}
