apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-{{ .Values.global.environment.config.dina_export_api.label }}
spec:
  replicas: {{ if and .Values.profiles.export_api.enabled (not (or .Values.global.environment.config.db_init.restore_db .Values.global.environment.config.db_init.reset_users)) }}1{{ else }}0{{ end }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-{{ .Values.global.environment.config.dina_export_api.label }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}-{{ .Values.global.environment.config.dina_export_api.label }}
    spec:
      initContainers:
        {{- include "dina-helm.initContainer.checkDb" . | nindent 8 }}
        {{- include "dina-helm.initContainer.initDb" (dict "root" . "serviceKey" "dinaexportapi" "environmentKey" "dina_export_api" "shortName" "export") | nindent 8 }}
      containers:
        - name: dina-export-api
          {{- with .Values.dinaexportapi.image }}
          image: {{ include "dina-helm.build-image-name" . | quote }}
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" | quote }}
          {{- end }}
          {{- if .Values.messageProducerOverride.enabled }}
          envFrom:
            - configMapRef:
                name: message-producer-override-exportapi
          {{- end }}
          env:
            - name: KEYCLOAK_ENABLED
              value: {{ .Values.global.environment.keycloak.enabled | quote }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              value: {{ tpl .Values.global.environment.spring.security.oauth2.resourceserver.jwt.issuer_uri . | quote }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
              value: {{ tpl .Values.global.environment.spring.security.oauth2.resourceserver.jwt.jwk_set_uri . | quote }}
            - name: SPRING_DATASOURCE_URL
              value: {{ tpl .Values.services.dinaexportapi.environment.spring.datasource.url . }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.services.dinaexportapi.environment.spring.datasource.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              {{- if .Values.services.dinaexportapi.environment.spring.datasource.password }}
              value: {{ .Values.services.dinaexportapi.environment.spring.datasource.password }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: dinaexportapi-datasource-secret
                  key: password
              {{- end }}
            - name: SPRING_LIQUIBASE_USER
              value: {{ tpl .Values.services.initdb.config.dinaexportapi.spring.liquibase.username . }}
            - name: SPRING_LIQUIBASE_PASSWORD
              {{- if .Values.services.dinaexportapi.environment.spring.liquibase.password }}
              value: {{ .Values.services.dinaexportapi.environment.spring.liquibase.password }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: dinaexportapi-liquibase-secret
                  key: password
              {{- end }}
            - name: SPRING_FREEMARKER_TEMPLATE-LOADER-PATH
              value: {{ .Values.services.dinaexportapi.environment.spring.freemarker.template_loader_path }}
            - name: DINA_EXPORT_WORKINGFOLDER
              value: {{ .Values.services.dinaexportapi.environment.dina.export.workingFolder }}
            - name: ELASTICSEARCH_HOST
              value: {{ tpl .Values.services.dinaexportapi.environment.elasticsearch.host . }}
            - name: ELASTICSEARCH_PORT
              value: {{ .Values.services.dinaexportapi.environment.elasticsearch.port | quote }}
            - name: ELASTICSEARCH_USERNAME
              value: {{ tpl .Values.services.dinaexportapi.environment.elasticsearch.username . }}
            - name: ELASTICSEARCH_PASSWORD
              {{- if not .Values.global.environment.config.elasticsearch.password }}
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: password
              {{- else }}
              value: {{ tpl .Values.global.environment.config.elasticsearch.password . }}
              {{- end }}
            - name: ELASTICSEARCH_CERTPATH
              value: {{ tpl .Values.services.dinaexportapi.environment.elasticsearch.certPath . }}
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 1
          volumeMounts:
            - name: dina-export-pv
              mountPath: /tmp/templates
            - name: es-certs
              mountPath: /app/certs
          resources:
            requests:
              memory: {{ .Values.resources.apis.requests.memory }}
              cpu: {{ .Values.resources.apis.requests.cpu }}            
            limits:
              memory: {{ .Values.resources.apis.limits.memory }} 
              cpu: {{ .Values.resources.apis.limits.cpu }}
      volumes:
        - name: dina-export-pv
          emptyDir: {}
        - name: es-certs
          persistentVolumeClaim:
            claimName: es-certs-{{ .Values.app.name }}-elasticsearch-dina-0
status: {}
