apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-elasticsearch-dina
spec:
  serviceName: {{ .Values.app.name }}-elasticsearch-dina
  replicas: {{ if and .Values.profiles.search_api.enabled (not (or .Values.global.environment.config.db_init.restore_db .Values.global.environment.config.db_init.reset_users)) }}1{{ else }}0{{ end }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-elasticsearch-dina
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-elasticsearch-dina
    spec:
      containers:
        - name: elasticsearch-dina
          image: {{ .Values.services.elasticsearchdina.image }}
          command:
          - /bin/bash
          - -ce
          args:
          - |
            /usr/share/elasticsearch/bin/elasticsearch-plugin install analysis-icu &&
            echo 'ElasticSearch is restarting' &&
            /usr/share/elasticsearch/scripts/entrypoint.sh
          env:
            - name: ELASTIC_PASSWORD
              {{- if not .Values.global.environment.config.elasticsearch.password }}
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: password
              {{- else }}
              value: {{ tpl .Values.global.environment.config.elasticsearch.password . }}
              {{- end }}
            - name: xpack.security.enabled
              value: {{ .Values.services.elasticsearchdina.environment.xpack.security.enabled | quote }}
            - name: xpack.security.http.ssl.enabled
              value: {{ .Values.services.elasticsearchdina.environment.xpack.security.http.ssl.enabled | quote }}
            - name: xpack.security.http.ssl.key
              value: {{ .Values.services.elasticsearchdina.environment.xpack.security.http.ssl.key | quote }}
            - name: xpack.security.http.ssl.certificate
              value: {{ .Values.services.elasticsearchdina.environment.xpack.security.http.ssl.certificate | quote }}
            - name: xpack.security.http.ssl.certificate_authorities
              value: {{ .Values.services.elasticsearchdina.environment.xpack.security.http.ssl.certificate_authorities | quote }}
            - name: xpack.security.transport.ssl.enabled
              value: {{ .Values.services.elasticsearchdina.environment.xpack.security.transport.ssl.enabled | quote }}
            - name: xpack.security.transport.ssl.verification_mode
              value: {{ .Values.services.elasticsearchdina.environment.xpack.security.transport.ssl.verification_mode | quote }}
            - name: xpack.security.transport.ssl.client_authentication
              value: {{ .Values.services.elasticsearchdina.environment.xpack.security.transport.ssl.client_authentication | quote }}
            - name: xpack.security.transport.ssl.keystore.path
              value: {{ .Values.services.elasticsearchdina.environment.xpack.security.transport.ssl.keystore.path | quote }}
            - name: xpack.security.transport.ssl.truststore.path
              value: {{ .Values.services.elasticsearchdina.environment.xpack.security.transport.ssl.truststore.path | quote }}
            - name: discovery.type
              value: {{ .Values.services.elasticsearchdina.environment.discovery.type }}
            - name: action.auto_create_index
              value: {{ .Values.services.elasticsearchdina.environment.action.auto_create_index | quote }}
          ports:
            - name: http
              containerPort: 9200
            - name: internal
              containerPort: 9300
          {{- if .Values.global.environment.securityContext.enabled }}
          securityContext:
            capabilities:
              add: ["IPC_LOCK"]
            runAsUser: 1000
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: 9200
            initialDelaySeconds: 5
            periodSeconds: 1
          resources:
            requests:
              memory: {{ .Values.resources.general.requests.memory }}
              cpu: {{ .Values.resources.general.requests.cpu }}            
            limits:
              memory: {{ .Values.resources.general.limits.memory }} 
              cpu: {{ .Values.resources.general.limits.cpu }}
          volumeMounts:
            - name: es-data
              mountPath: /usr/share/elasticsearch/data
            - name: es-certs
              mountPath: /usr/share/elasticsearch/config/certs/
            - name: es-scripts
              mountPath: /usr/share/elasticsearch/scripts
      volumes:
        - name: es-scripts
          configMap:
            name: elasticsearch-scripts
            defaultMode: 0555
            items:
            - key: entrypoint.sh
              path: entrypoint.sh
  volumeClaimTemplates:
  - metadata:
      name: es-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.global.environment.storageClass }}
      resources:
        requests:
          storage: 1Gi
  - metadata:
      name: es-certs
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: {{ .Values.global.environment.storageClassRWX }}
      resources:
        requests:
          storage: 10Mi
status: {}
