apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-elastic-configurator
spec:
  ttlSecondsAfterFinished: 60
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}-elastic-configurator
    spec:
      restartPolicy: OnFailure
      initContainers:
      - name: check-elasticsearch
        image: appropriate/curl
        command:
          - sh
          - -c
        args:
        - |
          set -e
          ELASTICSEARCH_URL="http://elasticsearch-service:9200"
          until curl -s "$ELASTICSEARCH_URL" > /dev/null
          do
              echo "Waiting for Elasticsearch service to be available..."
              sleep 5
          done
          echo "Elasticsearch service is available."
      containers:
        - name: elastic-configurator
          image: {{ .Values.services.elasticconfigurator.image }}
          env:
            - name: ELASTIC_SERVER_URL
              value: {{ .Values.services.elasticconfigurator.environment.ELASTIC_SERVER_URL }}
            - name: INDEX_CREATE_CMD
              value: {{ .Values.services.elasticconfigurator.environment.INDEX_CREATE_CMD }}
            - name: DINA_INDEX_DECLARATIONS
              value: {{ .Values.services.elasticconfigurator.environment.DINA_INDEX_DECLARATIONS }}
            - name: DINA_AGENT_INDEX_NAME
              value: {{ .Values.services.elasticconfigurator.environment.DINA_AGENT_INDEX_NAME }}
            - name: DINA_AGENT_INDEX_SETTINGS_FILE
              value: {{ .Values.services.elasticconfigurator.environment.DINA_AGENT_INDEX_SETTINGS_FILE }}
            - name: DINA_MATERIAL_SAMPLE_INDEX_NAME
              value: {{ .Values.services.elasticconfigurator.environment.DINA_MATERIAL_SAMPLE_INDEX_NAME }}
            - name: DINA_MATERIAL_SAMPLE_INDEX_SETTINGS_FILE
              value: {{ .Values.services.elasticconfigurator.environment.DINA_MATERIAL_SAMPLE_INDEX_SETTINGS_FILE }}
            - name: DINA_STORAGE_INDEX_NAME
              value: {{ .Values.services.elasticconfigurator.environment.DINA_STORAGE_INDEX_NAME }}
            - name: DINA_STORAGE_INDEX_SETTINGS_FILE
              value: {{ .Values.services.elasticconfigurator.environment.DINA_STORAGE_INDEX_SETTINGS_FILE }}
            - name: DINA_OBJECT_STORE_INDEX_NAME
              value: {{ .Values.services.elasticconfigurator.environment.DINA_OBJECT_STORE_INDEX_NAME }}
            - name: DINA_OBJECT_STORE_INDEX_SETTINGS_FILE
              value: {{ .Values.services.elasticconfigurator.environment.DINA_OBJECT_STORE_INDEX_SETTINGS_FILE }}
            - name: DINA_TRANSACTION_INDEX_NAME
              value: {{ .Values.services.elasticconfigurator.environment.DINA_TRANSACTION_INDEX_NAME }}
            - name: DINA_TRANSACTION_INDEX_SETTINGS_FILE
              value: {{ .Values.services.elasticconfigurator.environment.DINA_TRANSACTION_INDEX_SETTINGS_FILE }}
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 1
          resources:
            requests:
              memory: {{ .Values.resources.apis.requests.memory }}
              cpu: {{ .Values.resources.apis.requests.cpu }}            
            limits:
              memory: {{ .Values.resources.apis.limits.memory }} 
              cpu: {{ .Values.resources.apis.limits.cpu }}
          volumeMounts:
            - name: elastic-pv
              mountPath: /usr/share/elastic-configurator/settings
      volumes:
        - name: elastic-pv
          hostPath:
            path: "{{tpl .Values.workingDirPath . }}/elastic-configurator-settings"
status: {}
