apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-keycloak
spec:
  replicas: {{ if (not (or .Values.global.environment.config.db_init.restore_db .Values.global.environment.config.db_init.reset_users)) }}1{{ else }}0{{ end }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-keycloak
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  template:
    metadata:
      annotations: {}
      labels:
        app: {{ .Values.app.name }}-keycloak
    spec:
      initContainers:
        {{- include "dina-helm.initContainer.checkDb" . | nindent 8 }}
        - name: init-keycloak-schema
          {{- with .Values.initdb.image }}
          image: {{ include "dina-helm.build-image-name" . | quote }}
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" | quote }}
          {{- end }}
          command: ["/bin/bash", "-ce"]
          args:
            - |
              export POSTGRES_DB="$DB_NAME"
              /work/createUser.sh "${DB_NAME}" "${DB_USER}" "${DB_PASSWORD}"
              export PGPASSWORD="$POSTGRES_PASSWORD"
              echo "Creating schema $DB_SCHEMA in database $DB_NAME with authorization to user $DB_USER if it does not exist..."
              psql -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -d "$DB_NAME" -c "CREATE SCHEMA IF NOT EXISTS \"$DB_SCHEMA\";"
              psql -h "$POSTGRES_HOST" -U "$POSTGRES_USER" -d "$DB_NAME" -c "ALTER SCHEMA \"$DB_SCHEMA\" OWNER TO \"$DB_USER\";"
          env:
          - name: POSTGRES_HOST
            value: {{ tpl .Values.services.initdb.environment.POSTGRES_HOST . }}
          - name: POSTGRES_USER
            value: {{ tpl .Values.services.initdb.environment.POSTGRES_USER . }}
          - name: DB_NAME
            value: {{ tpl .Values.services.keycloak.environment.KC_DB_URL_DATABASE . }}
          - name: DB_SCHEMA
            value: "keycloak"
          - name: DB_USER
            value: {{ tpl .Values.services.keycloak.environment.KC_DB_USERNAME . }}
          - name: POSTGRES_PASSWORD
            {{- if not .Values.global.environment.config.dina_db.db_password }}
            valueFrom:
              secretKeyRef:
                name: dina-db-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.environment.POSTGRES_PASSWORD . }}
            {{- end }}
          - name: DB_PASSWORD
            {{- if not .Values.global.environment.config.keycloak.db_password }}
            valueFrom:
              secretKeyRef:
                name: keycloak-db-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.keycloak.environment.KC_DB_PASSWORD . }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources.initcontainers | nindent 12 }}
      containers:
        - name: keycloak
          {{- with .Values.keycloak.image }}
          image: {{ include "dina-helm.build-image-name" . | quote }}
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" | quote }}
          {{- end }}
          command:
          - /bin/bash
          - -ce
          args:
          - |
            /opt/keycloak/bin/kc.sh build --db=postgres --http-relative-path=/auth
            /opt/keycloak/bin/kc.sh start --import-realm --optimized
          env:
            - name: KC_DB_PASSWORD
              {{- if not .Values.global.environment.config.keycloak.db_password }}
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-secret
                  key: password
              {{- else }}
              value: {{ tpl .Values.services.keycloak.environment.KC_DB_PASSWORD . }}
              {{- end }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              {{- if not .Values.global.environment.config.keycloak.keycloak_admin_password }}
              valueFrom:
                secretKeyRef:
                  name: keycloak-admin-secret
                  key: password
              {{- else }}
              value: {{ tpl .Values.services.keycloak.environment.KEYCLOAK_ADMIN_PASSWORD . }}
              {{- end }}
            - name: KC_DB_URL_DATABASE
              value: {{ tpl .Values.services.keycloak.environment.KC_DB_URL_DATABASE . }}
            - name: KC_DB_URL_HOST
              value: {{ tpl .Values.services.keycloak.environment.KC_DB_URL_HOST . }}
            - name: KC_DB_SCHEMA
              value: "keycloak"
            - name: KC_DB_USERNAME
              value: {{ tpl .Values.services.keycloak.environment.KC_DB_USERNAME . }}
            - name: KC_HOSTNAME
              value: {{ tpl .Values.services.keycloak.environment.KC_HOSTNAME . }}
            - name: KC_HOSTNAME_ADMIN
              value: {{ tpl .Values.services.keycloak.environment.KC_HOSTNAME_ADMIN . }}
            - name: KC_PROXY
              value: {{ .Values.services.keycloak.environment.KC_PROXY }}
            - name: KEYCLOAK_ADMIN
              value: {{ tpl .Values.services.keycloak.environment.KEYCLOAK_ADMIN . }}
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /auth/realms/master
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            requests:
              memory: {{ .Values.resources.general.requests.memory }}
              cpu: {{ .Values.resources.general.requests.cpu }}            
            limits:
              memory: {{ .Values.resources.general.limits.memory }} 
              cpu: {{ .Values.resources.general.limits.cpu }}
          volumeMounts:
            - name: keycloak-dina-starter-volume
              mountPath: /opt/keycloak/data/import
            - name: keycloak-theme-volume
              mountPath: /opt/keycloak/themes/dina/login
            - name: keycloak-scripts
              mountPath: /opt/keycloak/scripts
            - name: certs-volume
              mountPath: /etc/certs
            - name: ldap-certs
              mountPath: /opt/keycloak/conf/truststores/
      volumes:
        - name: keycloak-dina-starter-volume
          configMap:
            name: keycloak-realm
        - name: keycloak-scripts
          configMap:
            name: scripts-configmap
        - name: keycloak-theme-volume
          configMap:
            name: keycloak-theme
            items:
            - key: login.ftl
              path: login.ftl
            - key: theme.properties
              path: theme.properties
            - key: dina-login.css
              path: resources/css/dina-login.css
            - key: dina.png
              path: resources/img/dina-tr-1344-1184.png
        - name: certs-volume
          configMap:
            name: certs
        - name: ldap-certs
          configMap:
            name: keycloak-certificates
status: {}
