apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-minio 
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}-minio
    spec:
      containers:
        - name: minio
          image: {{ .Values.services.minio.image }}
          command:
          - bin/bash
          - -ce
          args:
          - |
            minio server /data
          env:
            - name: MINIO_ROOT_USER
              value: {{ .Values.services.minio.environment.MINIO_ACCESS_KEY }}         
            - name: MINIO_ROOT_PASSWORD
              value: {{ .Values.services.minio.environment.MINIO_SECRET_KEY }}
            - name: MINIO_VOLUMES
              value: /data
          resources:
            requests:
              memory: {{ .Values.resources.general.requests.memory }}
              cpu: {{ .Values.resources.general.requests.cpu }}            
            limits:
              memory: {{ .Values.resources.general.limits.memory }} 
              cpu: {{ .Values.resources.general.limits.cpu }} 
          volumeMounts:
            - name: minio-pv
              mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: minio-pv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "standard"
      resources:
        requests:
          storage: 2Gi
status: {}
