# Persistent Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.name }}-object-store-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes: 
  - {{ .Values.services.objectstoreapi.storage.accessModes }}
  storageClassName: {{ .Values.global.environment.storageClass }}
  resources:
    requests:
      storage: {{ .Values.resources.objectstoreapi.storage_limit_gb }}Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-{{ .Values.global.environment.config.objectstore_api.label }}
spec:
  replicas: {{ if and .Values.profiles.object_store_api.enabled (not (or .Values.global.environment.config.db_init.restore_db .Values.global.environment.config.db_init.reset_users)) }}1{{ else }}0{{ end }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-{{ .Values.global.environment.config.objectstore_api.label }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}-{{ .Values.global.environment.config.objectstore_api.label }}
    spec:
      initContainers:
        {{- include "dina-helm.initContainer.checkDb" . | nindent 8 }}
        {{- include "dina-helm.initContainer.initDb" (dict "root" . "serviceKey" "objectstoreapi" "environmentKey" "objectstore_api" "shortName" "object_store") | nindent 8 }}
      containers:
        - name: object-store-api
          {{- with .Values.objectstoreapi.image }}
          image: {{ include "dina-helm.build-image-name" . | quote }}
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" | quote }}
          {{- end }}
          {{- if .Values.messageProducerOverride.enabled }}
          envFrom:
            - configMapRef:
                name: message-producer-override-objectstore
          {{- end }}
          env:
            - name: KEYCLOAK_ENABLED
              value: {{ .Values.global.environment.keycloak.enabled | quote }}
            - name: DEV-USER_ENABLED
              value: "false"
            - name: SPRING_SERVLET_MULTIPART_MAX-FILE-SIZE
              value: {{ .Values.services.objectstoreapi.environment.spring.servlet.multipart.max_file_size }}
            - name: SPRING_SERVLET_MULTIPART_MAX-REQUEST-SIZE
              value: {{ .Values.services.objectstoreapi.environment.spring.servlet.multipart.max_request_size }}
            - name: S3_ENDPOINT
              value: {{ tpl .Values.services.objectstoreapi.environment.s3.endpoint . }}
            - name: S3_ACCESSKEY
              value: {{ tpl .Values.services.objectstoreapi.environment.s3.accessKey . }}
            - name: S3_SECRETKEY
              value: {{ tpl .Values.services.objectstoreapi.environment.s3.secretKey . }}         
            - name: DINA_FILESTORAGE_IMPLEMENTATION
              value: {{ tpl .Values.services.objectstoreapi.environment.dina.fileStorage.implementation . }}
            - name: DINA_FILESTORAGE_ROOT
              value: {{ tpl .Values.services.objectstoreapi.environment.dina.fileStorage.root . }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              value: {{ tpl .Values.global.environment.spring.security.oauth2.resourceserver.jwt.issuer_uri . | quote }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
              value: {{ tpl .Values.global.environment.spring.security.oauth2.resourceserver.jwt.jwk_set_uri . | quote }}
            - name: SPRING_DATASOURCE_URL
              value: {{ tpl .Values.services.objectstoreapi.environment.spring.datasource.url . }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.services.objectstoreapi.environment.spring.datasource.username }}
            - name: SPRING_DATASOURCE_PASSWORD
              {{- if .Values.services.objectstoreapi.environment.spring.datasource.password }}
              value: {{ .Values.services.objectstoreapi.environment.spring.datasource.password }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: objectstoreapi-datasource-secret
                  key: password
              {{- end }}
            - name: SPRING_LIQUIBASE_USER
              value: {{ tpl .Values.services.initdb.config.objectstoreapi.spring.liquibase.username . }}
            - name: SPRING_LIQUIBASE_PASSWORD
              {{- if .Values.services.objectstoreapi.environment.spring.liquibase.password }}
              value: {{ .Values.services.objectstoreapi.environment.spring.liquibase.password }}
              {{- else }}
              valueFrom:
                secretKeyRef:
                  name: objectstoreapi-liquibase-secret
                  key: password
              {{- end }}
            - name: JDK_JAVA_OPTIONS
              value: "{{ .Values.services.objectstoreapi.config.java_opts }}"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 1
          resources:
            requests:
              memory: {{ .Values.resources.apis.requests.memory }}
              cpu: {{ .Values.resources.apis.requests.cpu }}            
            limits:
              memory: {{ .Values.resources.objectstoreapi.memory_limit_mb }}M
              cpu: {{ .Values.resources.objectstoreapi.cpu_limit_m }}m

          volumeMounts:
            - name: {{.Values.services.objectstoreapi.storage.volumeName}}
              mountPath: {{ .Values.services.objectstoreapi.environment.dina.fileStorage.root }}

      volumes:
        - name: {{ .Values.services.objectstoreapi.storage.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.app.name }}-object-store-pvc
        
status: {}
