apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-search-ws
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: {{ if .Values.profiles.search_api.enabled }}1{{ else }}0{{ end }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-search-ws
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}-search-ws
    spec:
      containers:
        - name: search-ws
          image: {{ .Values.services.searchws.image }}
          env:
            - name: ELASTICSEARCH_HOST
              value: {{ tpl .Values.services.searchws.environment.elasticsearch.host . }}
          ports:
            - name: http
              containerPort: 8085
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 1
          resources:
            requests:
              memory: {{ .Values.resources.apis.requests.memory }}
              cpu: {{ .Values.resources.apis.requests.cpu }}            
            limits:
              memory: {{ .Values.resources.apis.limits.memory }} 
              cpu: {{ .Values.resources.apis.limits.cpu }}
