apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-search-ws
spec:
  replicas: {{ if and .Values.profiles.search_api.enabled (not (or .Values.global.environment.config.db_init.restore_db .Values.global.environment.config.db_init.reset_users)) }}1{{ else }}0{{ end }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-search-ws
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}-search-ws
    spec:
      containers:
        - name: search-ws
          {{- with .Values.searchws.image }}
          image: {{ include "dina-helm.build-image-name" . | quote }}
          imagePullPolicy: {{ .pullPolicy | default "IfNotPresent" | quote }}
          {{- end }}
          env:
            - name: KEYCLOAK_ENABLED
              value: {{ .Values.global.environment.keycloak.enabled | quote }}
            - name: ELASTICSEARCH_HOST
              value: {{ tpl .Values.services.searchws.environment.elasticsearch.host . }}
            - name: ELASTICSEARCH_USERNAME
              value: {{ tpl .Values.services.searchws.environment.elasticsearch.username . }}
            - name: ELASTICSEARCH_PASSWORD
              {{- if not .Values.global.environment.config.elasticsearch.password }}
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-secret
                  key: password
              {{- else }}
              value: {{ tpl .Values.global.environment.config.elasticsearch.password . }}
              {{- end }}
            - name: ELASTICSEARCH_CERTPATH
              value: {{ tpl .Values.services.searchws.environment.elasticsearch.certPath . }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI
              value: {{ tpl .Values.global.environment.spring.security.oauth2.resourceserver.jwt.issuer_uri . | quote }}
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI
              value: {{ tpl .Values.global.environment.spring.security.oauth2.resourceserver.jwt.jwk_set_uri . | quote }}
          ports:
            - name: http
              containerPort: 8085
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 5
            periodSeconds: 1
          resources:
            requests:
              memory: {{ .Values.resources.apis.requests.memory }}
              cpu: {{ .Values.resources.apis.requests.cpu }}            
            limits:
              memory: {{ .Values.resources.apis.limits.memory }} 
              cpu: {{ .Values.resources.apis.limits.cpu }}
          volumeMounts:
            - name: es-certs
              mountPath: /app/certs
      volumes:
        - name: es-certs
          persistentVolumeClaim:
            claimName: es-certs-{{ .Values.app.name }}-elasticsearch-dina-0