trigger: none

parameters:
- name: tag
  displayName: tag to use in Azure Container Registry (ACR)
  type: string
  default: dev
- name: pushACR
  displayName: Push to Azure Container Registry (ACR)
  type: boolean
  default: false
  
name: Build OKD RabbitMQ image

pool:
  vmImage: ubuntu-latest

variables:
  imageTag: 'rabbitmq-okd:${{ parameters.tag }}'
  AZ_SC: $(ServiceConnection)
  AZ_ACR: $(ContainerRegistry)
  
steps:
 - task: Docker@2
   displayName: Build an image
   inputs:
     tags: ${{ variables.AZ_ACR }}.azurecr.io/okd/$(imageTag)
     command: build
     Dockerfile: okd/Dockerfile-rabbitmq

 - task: AzureCLI@2
   displayName: Login and push to Azure Container Registry
   condition: ${{ eq(parameters.pushACR, true) }}
   inputs:
    connectedServiceNameARM: ${{ variables.AZ_SC }}
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az acr login --name ${{ variables.AZ_ACR }}.azurecr.io
      docker push ${{ variables.AZ_ACR }}.azurecr.io/okd/$(imageTag)
