apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:

  name: localstorage
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
reclaimPolicy: Retain
allowVolumeExpansion: True
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgresql-01
  labels:
    type: local
spec:
  storageClassName: localstorage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/postgresql01"
