apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-keycloak-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2500m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 12k
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.services.keycloak.environment.KC_HOSTNAME }}
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: keycloak-service
              port:
                number: 80
    - host: "*."{{ .Values.services.keycloak.environment.KC_HOSTNAME }}
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: keycloak-service
              port:
                number: 80  
