apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-keycloak
  labels:
    app: {{ .Values.app.name }}-keycloak
spec:
  type: ClusterIP
  ports:
    - port: 8443
      targetPort: 8443
      name: https-service-port
    - port: 8080
      name: http-service-port
      targetPort: 8080
  selector:
    app: {{ .Values.app.name }}-keycloak
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-keycloak-db
  labels:
    app: {{ .Values.app.name }}-keycloak-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: {{ .Values.app.name }}-keycloak-db
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-dina-db
  labels:
    app: {{ .Values.app.name }}-dina-db
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http

  selector:
    app: {{ .Values.app.name }}-dina-db