# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- test-ADO-pipeline

pool:
  vmImage: ubuntu-latest

steps:
- bash: docker compose -f docker-compose.base.yml up &
# - task: DockerCompose@0
#   inputs:
#     containerregistrytype: 'Container Registry'
#     dockerComposeFile: 'docker-compose.base.yml'
#     action: 'Run a Docker Compose command'
#     dockerComposeCommand: 'up'
- bash: curl --head -X GET --retry 25 --retry-connrefused --retry-delay 1 http://keycloak:8080
- bash: docker compose -f docker-compose.base.yml down

    