# dina-local-deployment pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: dinaLocalCertificate
  displayName: 'Download DINA local certificate'
  inputs:
    secureFile: 'dina-local-cert.pem'

- script: |
    displayName: 'Installing local-deployement Certificates'
    echo Installing $(dinaLocalCertificate.secureFilePath) to the trusted CA directory...
    sudo chown root:root $(dinaLocalCertificate.secureFilePath)
    sudo chmod a+r $(dinaLocalCertificate.secureFilePath)
    sudo ln -s -t /etc/ssl/certs/ $(dinaLocalCertificate.secureFilePath)
    echo Installing $(dinaLocalCertificate.secureFilePath) in $(System.AccessToken)/certs
    cp $(dinaLocalCertificate.secureFilePath) $(Pipeline.Workspace)/certs

#- bash: docker compose -f docker-compose.base.yml up &
# - task: DockerCompose@0
#   inputs:
#     containerregistrytype: 'Container Registry'
#     dockerComposeFile: 'docker-compose.base.yml'
#     action: 'Run a Docker Compose command'
#     dockerComposeCommand: 'up'
#- bash: curl --head -X GET --retry 25 --retry-connrefused --retry-delay 1 http://keycloak:8080
#- bash: docker compose -f docker-compose.base.yml down

    