# dina-local-deployment pipeline

trigger:
- master

name: dina-local-deployment pipeline

pool:
  vmImage: ubuntu-latest

steps:
- task: DownloadSecureFile@1
  name: dinaLocalCertificate
  displayName: 'Download DINA local certificate'
  inputs:
    secureFile: 'dina-local-cert.pem'
- task: DownloadSecureFile@1
  name: dinaLocalCertificateKey
  displayName: 'Download DINA local certificate key'
  inputs:
    secureFile: 'dina-local-key.pem'

- script: |
    echo Installing $(dinaLocalCertificate.secureFilePath) to the trusted CA directory...
    sudo chown root:root $(dinaLocalCertificate.secureFilePath)
    sudo chmod a+r $(dinaLocalCertificate.secureFilePath)
    sudo chown root:root $(dinaLocalCertificateKey.secureFilePath)
    sudo chmod a+r $(dinaLocalCertificateKey.secureFilePath)
    sudo ln -s -t /etc/ssl/certs/ $(dinaLocalCertificate.secureFilePath)
    echo Installing $(dinaLocalCertificate.secureFilePath) in $(Pipeline.Workspace)/s/certs
    sudo cp $(dinaLocalCertificate.secureFilePath) $(Pipeline.Workspace)/s/certs/
    sudo cp $(dinaLocalCertificateKey.secureFilePath) $(Pipeline.Workspace)/s/certs/
  displayName: 'Setting up certificates'

- bash: docker compose -f docker-compose.base.yml -f docker-compose.local.yml up &
  displayName: 'Start DockerCompose'

- bash: |
    echo Try to connect to Keycloak endpoint ...
    curl --head -X GET --cacert /etc/ssl/certs/dina-local-cert.pem --retry 25 --retry-delay 1 --resolve dina.local:443:192.19.33.9 https://dina.local/auth
  displayName: 'Waiting for Keycloak ...'

- script: |
    wget -c https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.tgz
    tar -xf apache-jmeter-5.6.tgz
  displayName: 'Install the JMeter'

- script: |
    apache-jmeter-5.6/bin/./jmeter jmeter/collection_api_module_testplan.jmx -l results/results.jtl -e -o report
  displayName: 'Run JMeter'

- bash: docker compose -f docker-compose.base.yml down
  displayName: 'Stop DockerCompose'
