# dina-local-deployment pipeline

trigger:
- master

name: dina-local-deployment pipeline

pool:
  vmImage: ubuntu-latest

steps:

- script: |
    sudo sh -c "echo '192.19.33.9 dina.local' >> /etc/hosts"
    sudo sh -c "echo '192.19.33.9 api.dina.local' >> /etc/hosts"
    sudo sh -c "echo '192.19.33.9 keycloak.dina.local' >> /etc/hosts"
  displayName: 'Setting up hosts name'

- script: |
    sudo apt-get install wget libnss3-tools -y
    wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.3/mkcert-v1.4.3-linux-amd64
    sudo chmod +x mkcert-v1.4.3-linux-amd64
    sudo mv mkcert-v1.4.3-linux-amd64 /usr/bin/mkcert
    mkcert --install
    mkcert -cert-file  $(Pipeline.Workspace)/s/certs/dina-local-cert.pem -key-file $(Pipeline.Workspace)/s/certs/dina-local-key.pem "dina.local" "api.dina.local" "keycloak.dina.local"
  displayName: Setting up certificates

- bash: docker compose -f docker-compose.base.yml -f docker-compose.local.yml up &
  displayName: 'Start DockerCompose'

- bash: sleep 60
  displayName: 'Delay 60 Seconds'

- bash: |
    echo Try to connect to Keycloak endpoint ...
    curl --head -X GET --retry 25 --retry-delay 1 https://dina.local/auth
  displayName: 'Waiting for Keycloak ...'

- script: |
    wget -c https://dlcdn.apache.org/jmeter/binaries/apache-jmeter-5.6.1.tgz
    tar -xf apache-jmeter-5.6.1.tgz
  displayName: 'Install the JMeter'

- script: |
    echo Java version:
    java -version
    apache-jmeter-5.6.1/bin/./jmeter -n -t jmeter/collection_api_module_testplan.jmx -l results/results.jtl -e -o report -j jmeter.log
    echo Done
    cat jmeter.log
  displayName: 'Run JMeter'

- bash: docker compose -f docker-compose.base.yml -f docker-compose.local.yml down
  displayName: 'Stop DockerCompose'
