version: "3.9"
services:

  dina-ui:
    image: aafcbicoe/dina-ui:0.124.0
    environment:
      KEYCLOAK_CLIENTID: dina-public
      KEYCLOAK_REALM: dina
      KEYCLOAK_PUBLIC_URL: ${KEYCLOAK_EXTERNAL_URL}
      OBJECTSTORE_API_ADDRESS: object-store-api:8080
      AGENT_API_ADDRESS: agent-api:8080
      SEQDB_API_ADDRESS: seqdb-api:8080
      COLLECTION_API_ADDRESS: collection-api:8080
      USER_API_ADDRESS: dina-user-api:8080
      SEARCH_API_ADDRESS: search-ws:8085
      LOAN_TRANSACTION_API_ADDRESS: loan-transaction-api:8080
      REPORT_LABEL_API_ADDRESS: report-label-api:80
      INSTANCE_MODE: ${INSTANCE_MODE}
    networks:
      - dina
    ports:
      - "2015:80"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ui.tls=true"
      - "traefik.http.routers.ui.rule=Host(`${DINA_UI_HOSTNAME}`)"
      - "traefik.http.services.ui.loadbalancer.server.port=8080"

  seqdb-api:
    image: aafcbicoe/seqdb-api:2.8.0
    profiles: ["seqdb_api"]
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: ${KEYCLOAK_INTERNAL_URL}
      spring.datasource.url: jdbc:postgresql://dina-db/seqdb?currentSchema=seqdb
      spring.liquibase.user: ${SEQDB_MIGRATION_USER}
      spring.liquibase.password: ${SEQDB_MIGRATION_USER_PW}
      spring.datasource.username: ${SEQDB_WEB_USER}
      spring.datasource.password: ${SEQDB_WEB_USER_PW}
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      # Opens http://api.dina.local/seqdb/api/ module endpoint
      - "traefik.http.middlewares.stripseqdb.stripprefix.prefixes=${SEQDB_API_PREFIX}"
      - "traefik.http.routers.seqdbapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${SEQDB_API_PREFIX}/`)"
      - "traefik.http.routers.seqdbapi.middlewares=stripseqdb@docker"
    depends_on:
      init-db:
        condition: service_completed_successfully 

  agent-api:
    image: aafcbicoe/agent-api:0.23
    profiles: ["agent_api"]
    mem_limit: 512m
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: ${KEYCLOAK_INTERNAL_URL}
      spring.datasource.url: jdbc:postgresql://dina-db/agent?currentSchema=agent
      spring.liquibase.user: ${AGENT_MIGRATION_USER}
      spring.liquibase.password: ${AGENT_MIGRATION_USER_PW}
      spring.datasource.username: ${AGENT_WEB_USER}
      spring.datasource.password: ${AGENT_WEB_USER_PW}
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      # Opens http://api.dina.local/agent/api/v1/ module endpoint
      - "traefik.http.middlewares.stripagent.stripprefix.prefixes=${AGENT_API_PREFIX}"
      - "traefik.http.routers.agentapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${AGENT_API_PREFIX}/`)"
      - "traefik.http.routers.agentapi.middlewares=stripagent@docker"
      - "traefik.docker.network=dina-local-deployment_dina"
    depends_on:
      init-db:
        condition: service_completed_successfully 

  collection-api:
    image: aafcbicoe/natural-history-collection-api:0.76
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: ${KEYCLOAK_INTERNAL_URL}
      spring.datasource.url: jdbc:postgresql://dina-db/collection?currentSchema=collection
      spring.liquibase.user: ${COLL_MIGRATION_USER}
      spring.liquibase.password: ${COLL_MIGRATION_USER_PW}
      spring.liquibase.contexts: schema-change, initial-data, data-migration
      spring.datasource.username: ${COLL_WEB_USER}
      spring.datasource.password: ${COLL_WEB_USER_PW}
      actuator.allowedIp: prometheus
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      # Opens http://api.dina.local/collection/api/v1 module endpoint
      - "traefik.http.middlewares.stripcollection.stripprefix.prefixes=${COLLECTION_API_PREFIX}"
      - "traefik.http.routers.collectionapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${COLLECTION_API_PREFIX}/`)"
      - "traefik.http.routers.collectionapi.middlewares=stripcollection@docker"
      - "traefik.docker.network=dina-local-deployment_dina"
    depends_on:
      init-db:
        condition: service_completed_successfully 

  loan-transaction-api:
    image: aafcbicoe/loan-transaction-api:0.8
    profiles: ["loan_transaction_api"]
    mem_limit: 512m
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: ${KEYCLOAK_INTERNAL_URL}
      spring.datasource.url: jdbc:postgresql://dina-db/loan_transaction?currentSchema=loan_transaction
      spring.liquibase.user: ${LOAN_TRANSACTION_MIGRATION_USER}
      spring.liquibase.password: ${LOAN_TRANSACTION_MIGRATION_USER_PW}
      spring.liquibase.contexts: schema-change, initial-data, data-migration
      spring.datasource.username: ${LOAN_TRANSACTION_WEB_USER}
      spring.datasource.password: ${LOAN_TRANSACTION_WEB_USER_PW}
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      # Opens http://api.dina.local/transaction/api/v1 module endpoint
      - "traefik.http.middlewares.striploantransaction.stripprefix.prefixes=${LOAN_TRANSACTION_API_PREFIX}"
      - "traefik.http.routers.loantransactionapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${LOAN_TRANSACTION_API_PREFIX}/`)"
      - "traefik.http.routers.loantransactionapi.middlewares=striploantransaction@docker"
      - "traefik.docker.network=dina-local-deployment_dina"
    depends_on:
      init-db:
        condition: service_completed_successfully 

  dina-user-api:
    image: aafcbicoe/dina-user-api:0.14
    profiles: ["user_api"]
    mem_limit: 512m
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: ${KEYCLOAK_INTERNAL_URL}
      KEYCLOAK_USER_SVC_SECRET: 120c0b7a-5ed2-4295-9a31-29c2fcbc714f
      spring.datasource.url: jdbc:postgresql://dina-db/dina_user?currentSchema=dina_user
      spring.liquibase.user: ${DINA_USER_MIGRATION_USER}
      spring.liquibase.password: ${DINA_USER_MIGRATION_USER_PW}
      spring.datasource.username: ${DINA_USER_WEB_USER}
      spring.datasource.password: ${DINA_USER_WEB_USER_PW}
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      # Opens http://api.dina.local/dinauser/api/v1/ module endpoint
      - "traefik.http.middlewares.stripdinauser.stripprefix.prefixes=${DINA_USER_API_PREFIX}"
      - "traefik.http.routers.dinauserapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${DINA_USER_API_PREFIX}/`)"
      - "traefik.http.routers.dinauserapi.middlewares=stripdinauser@docker"
      - "traefik.http.services.dinauserapi.loadbalancer.server.port=8080"
    depends_on:
      init-db:
        condition: service_completed_successfully 

  object-store-api:
    image: aafcbicoe/object-store-api:1.4
    mem_limit: 1024m
    profiles: ["object_store_api"]
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: ${KEYCLOAK_INTERNAL_URL}
      dev-user.enabled: "false"
      spring.datasource.url: jdbc:postgresql://dina-db/object_store?currentSchema=object_store
      spring.liquibase.user: ${OBJ_STORE_MIGRATION_USER}
      spring.liquibase.password: ${OBJ_STORE_MIGRATION_USER_PW}
      spring.datasource.username: ${OBJ_STORE_WEB_USER}
      spring.datasource.password: ${OBJ_STORE_WEB_USER_PW}
      spring.servlet.multipart.max-file-size: 1GB
      spring.servlet.multipart.max-request-size: 1GB
      minio.host: minio
      minio.accessKey: ${MINIO_ACCESS_KEY}
      minio.secretKey: ${MINIO_SECRET_KEY}
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      # maps api.dina.local/objectstore/api/v1/... -> object_store_api/api/v1
      - "traefik.http.middlewares.stripobjectstore.stripprefix.prefixes=${OBJECT_STORE_API_PREFIX}"
      - "traefik.http.routers.objectstoreapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${OBJECT_STORE_API_PREFIX}/`)"
      - "traefik.http.routers.objectstoreapi.middlewares=stripobjectstore@docker"
      - "traefik.docker.network=dina-local-deployment_dina"
    depends_on:
      init-db:
        condition: service_completed_successfully 

  report-label-api:
    image: mfnberlin/dina-reports-labels:v1.1rc
    profiles: ["report_label_api"]
    volumes:
      - type: bind
        source: ./report-label/config.ini
        target: /usr/local/dina-labels/config.ini
      - type: bind
        source: ./report-label/templates
        target: /usr/local/dina-labels/templates
    labels:
      # Opens http://api.dina.local/collection/api/v1 module endpoint
      - "traefik.http.middlewares.striplabels.stripprefix.prefixes=${REPORT_LABEL_API_PREFIX}"
      - "traefik.http.routers.reportlabelapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${REPORT_LABEL_API_PREFIX}/`)"
      - "traefik.http.routers.reportlabelapi.middlewares=striplabels@docker"
    networks:
      - dina

  minio:
    image: minio/minio:RELEASE.2022-05-04T07-45-27Z
    profiles: ["object_store_api"]
    volumes:
      - ./minio-data:/data
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    networks:
      - dina

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch-dina:
    # we need a plugin so a custom image is built (to ensure an immutable Docker image)
    image: elasticsearch_icu:7.17.6
    build: elasticsearch/
    profiles: ["search_api"]
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - action.auto_create_index=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    networks:
      - dina
    ports:
      - 9200:9200
      - 9300:9300
    deploy:
      resources:
        limits:
          memory: 2000M
    labels:
      - "traefik.http.routers.elasticsearch.rule=Host(`elasticsearch-dina.localhost`)"

  # Addition of Kibana, for development purpose or browsing through the dina indices.
  kibana-dina:
    image: docker.elastic.co/kibana/kibana:7.16.2
    profiles: ["kibana"]
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch-dina:9200
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    networks:
      - dina
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch-dina

  prometheus:
    image: prom/prometheus
    profiles: ["prometheus"]
    ports:
      - "9090:9090"
    networks:
      - dina
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml

  # Check the status of elasticsearch and configure indices if not already present.
  elastic-configurator:
    image: aafcbicoe/es-init-container:0.6
    profiles: ["search_api"]
    environment:
      ELASTIC_SERVER_URL: $ELASTIC_SERVER_URL
      INDEX_CREATE_CMD: $INDEX_CREATE_CMD
      DINA_INDEX_DECLARATIONS: AGENT MATERIAL_SAMPLE STORAGE OBJECT_STORE TRANSACTION
      DINA_AGENT_INDEX_NAME: $DINA_AGENT_INDEX_NAME
      DINA_AGENT_INDEX_SETTINGS_FILE: $DINA_AGENT_INDEX_SETTINGS_FILE
      DINA_MATERIAL_SAMPLE_INDEX_NAME: $DINA_MATERIAL_SAMPLE_INDEX_NAME
      DINA_MATERIAL_SAMPLE_INDEX_SETTINGS_FILE: $DINA_MATERIAL_SAMPLE_INDEX_SETTINGS_FILE
      DINA_STORAGE_INDEX_NAME: $DINA_STORAGE_INDEX_NAME
      DINA_STORAGE_INDEX_SETTINGS_FILE: $DINA_STORAGE_INDEX_SETTINGS_FILE
      DINA_OBJECT_STORE_INDEX_NAME: $DINA_OBJECT_STORE_NAME
      DINA_OBJECT_STORE_INDEX_SETTINGS_FILE: $DINA_OBJECT_STORE_SETTINGS_FILE
      DINA_TRANSACTION_INDEX_NAME: $DINA_LOAN_TRANSACTION_INDEX_NAME
      DINA_TRANSACTION_INDEX_SETTINGS_FILE: $DINA_LOAN_TRANSACTION_INDEX_SETTINGS_FILE
    volumes:
      - ./elastic-configurator-settings:/usr/share/elastic-configurator/settings
    depends_on:
      - elasticsearch-dina
    networks:
      - dina

  search-ws:
    image: aafcbicoe/dina-search-ws:0.23
    mem_limit: 512m
    profiles: ["search_api"]
    networks:
      - dina
    labels:
      # maps api.dina.local/search... -> /search
      - "traefik.http.middlewares.stripsearchws.stripprefix.prefixes=${SEARCH_API_PREFIX}"
      - "traefik.http.routers.searchws.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${SEARCH_API_PREFIX}/`)"
      - "traefik.http.routers.searchws.middlewares=stripsearchws@docker"

  search-cli:
    image: aafcbicoe/dina-search-cli:0.23
    profiles: ["search_api"]
    environment:
      keycloak.openid_auth_server: ${KEYCLOAK_INTERNAL_URL}/realms/dina/protocol/openid-connect/token
      keycloak.client_id: dina-public
      keycloak.username: cnc-su
      keycloak.password: cnc-su
      ELASTICSEARCH_URL: elasticsearch-dina
      MATERIAL_SAMPLE_URL: http://collection-api:8080/api/v1/material-sample
      METADATA_URL: http://object-store-api:8080/api/v1/metadata
      ORGANIZATION_URL: http://agent-api:8080/api/v1/organization
      PERSON_URL: http://agent-api:8080/api/v1/person
      STORAGE_UNIT_URL: http://collection-api:8080/api/v1/storage-unit
      LOAN_TRANSACTION_URL: http://loan-transaction-api:8080/api/v1/transaction
      RABBITMQ_HOSTNAME: rabbitmq-dina
      IS_MESSAGE_CONSUMER: "true"
      IS_MESSAGE_PRODUCER: "true"
    stdin_open: true
    tty: true
    networks:
      - dina
      - dina_rabbitmq_net
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
      - api.dina.local:${TRAEFIK_IP}

  rabbitmq-dina:
    image: rabbitmq:3.8.20-management-alpine
    profiles: ["search_api"]
    container_name: 'rabbitmq-dina'
    hostname: rabbit_dina_node_1
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - dina_rabbitmq_net
        
  mockServer:
    image: mockserver/mockserver:mockserver-5.11.1
    profiles: ["mockServer"]
    ports:
      - 1080:1080
    environment:
      MOCKSERVER_PROPERTY_FILE: /usr/share/mock-server/config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /usr/share/mock-server/config/initializerJson.json
    volumes:
      - type: bind
        source: ./mock-server
        target: /usr/share/mock-server/config

volumes:
  elasticsearch-data:
    driver: local
  elastic-configurator-settings:
    driver: local      

networks:
  dina_rabbitmq_net:
    driver: bridge
    ipam:
      config:
        - subnet: ${RABBIT_SUBNET}
