version: "3.7"
services:
  object-store-api:
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT}/auth
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      # maps api.dina.local/objectstore/api/v1/... -> object_store_api/api/v1
      - "traefik.http.middlewares.stripobjectstore.stripprefix.prefixes=${OBJECT_STORE_API_PREFIX}"
      - "traefik.http.routers.objectstoreapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${OBJECT_STORE_API_PREFIX}/`)"
      - "traefik.http.routers.objectstoreapi.middlewares=stripobjectstore@docker"

  seqdb-api:
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT}/auth
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      # Opens http://api.dina.local/seqdb/api/ module endpoint
      - "traefik.http.middlewares.stripseqdb.stripprefix.prefixes=${SEQDB_API_PREFIX}"
      - "traefik.http.routers.seqdbapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${SEQDB_API_PREFIX}/`)"
      - "traefik.http.routers.seqdbapi.middlewares=stripseqdb@docker"

  collection-api:
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT}/auth
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      # Opens http://api.dina.local/collection/api/v1 module endpoint
      - "traefik.http.middlewares.stripcollection.stripprefix.prefixes=${COLLECTION_API_PREFIX}"
      - "traefik.http.routers.collectionapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${COLLECTION_API_PREFIX}/`)"
      - "traefik.http.routers.collectionapi.middlewares=stripcollection@docker"

  dina-ui:
    image: aafcbicoe/dina-ui:0.15.0
    environment:
      KEYCLOAK_CLIENTID: objectstore
      KEYCLOAK_REALM: dina
      KEYCLOAK_PUBLIC_URL: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT}/auth
      OBJECTSTORE_API_ADDRESS: object-store-api:8080
      AGENT_API_ADDRESS: agent-api:8080  
      SEQDB_API_ADDRESS: seqdb-api:8080
      COLLECTION_API_ADDRESS: collection-api:8080
    networks:
      - dina
    ports:
      - "2015:80"
    labels:
      - "traefik.http.routers.ui.rule=Host(`${DINA_UI_HOSTNAME}`)"
      - "traefik.http.services.ui.loadbalancer.server.port=8080"

  agent-api:
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT}/auth
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      # Opens http://api.dina.local/agent/api/v1/ module endpoint
      - "traefik.http.middlewares.stripagent.stripprefix.prefixes=${AGENT_API_PREFIX}"
      - "traefik.http.routers.agentapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${AGENT_API_PREFIX}/`)"
      - "traefik.http.routers.agentapi.middlewares=stripagent@docker"

  dina-user-api:
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT}/auth
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      # Opens http://api.dina.local/dinauser/api/v1/ module endpoint
      - "traefik.http.middlewares.stripdinauser.stripprefix.prefixes=${DINA_USER_API_PREFIX}"
      - "traefik.http.routers.dinauserapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${DINA_USER_API_PREFIX}/`)"
      - "traefik.http.routers.dinauserapi.middlewares=stripdinauser@docker"
      - "traefik.http.services.dinauserapi.loadbalancer.server.port=8080"
