version: "3.9"
networks:
  dina:
    ipam:
      config:
        - subnet: ${SUBNET}
services:
  traefik:
    image: traefik:v2.6.3
    command:
      # debug flags - may be commented or removed
      # Traefik dashboard: access localhost:8999 in browser
      - "--api.insecure=true"
      # access logs: use "docker logs --follow [traefik container]"
      - "--accesslog=true"
      # debug logging: enable the traefik.log volume to use these
      # - "--log.filePath=/traefik.log"
      # - "--log.level=DEBUG"
    ports:
      - "443:443"
      # 80 will be redirected to 443 by configuration
      - "80:80"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/traefik-dynamic.yml:/etc/traefik/dynamic.yml:ro
      - ./certs:/etc/certs:ro
      # Allow Traefik to log to a local file
      # - ./traefik.log:/traefik.log
    networks:
      dina:
        ipv4_address: ${TRAEFIK_IP}

  keycloak:
    build:
      context: keycloak/.
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_user
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
      KC_HTTPS_CERTIFICATE_FILE: /etc/certs/dina-local-cert.pem
      KC_HTTPS_CERTIFICATE_KEY_FILE: /etc/certs/dina-local-key.pem
    ports:
      - 8443:8443
    networks:
      dina:
    volumes:
      - ./keycloak-dina-starter-realm.json:/opt/keycloak/data/import/realm.json
      - ./certs:/etc/certs:ro
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.keycloak.rule=HostSNI(`${KEYCLOAK_HOSTNAME}`)"
      - "traefik.tcp.routers.keycloak.tls.passthrough=true"
      - "traefik.tcp.services.keycloak.loadbalancer.server.port=${KEYCLOAK_PORT}"
    depends_on:
      - keycloak-db

  keycloak-db:
    image: "postgres:12"
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_PASSWORD: keycloak_user
      POSTGRES_USER: keycloak_user
    networks:
      - dina
    volumes:
      - ./keycloak-data:/var/lib/postgresql/data
