version: "3.7"
services:
  object-store-api:
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT}/auth
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      - "traefik.http.routers.objectstoreapi.rule=Host(`${API_HOSTNAME}`)"
      - "traefik.http.routers.objectstoreapifromui.rule=Host(`${OBJECT_STORE_UI_HOSTNAME}`) && PathPrefix(`/api/`)"

  object-store-ui:
    build:
      context: ./dina-ui
      dockerfile: objectstore-ui.Dockerfile
    environment:
      KEYCLOAK_CLIENTID: objectstore
      KEYCLOAK_REALM: dina
      KEYCLOAK_PUBLIC_URL: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT}/auth
    networks:
      - dina
    ports:
      - "2015:80"
    labels:
      - "traefik.http.routers.ui.rule=Host(`${OBJECT_STORE_UI_HOSTNAME}`)"

