version: "3.9"
networks:
  dina:
    ipam:
      config:
        - subnet: ${SUBNET}
services:
  keycloak:
    image: jboss/keycloak:12.0.4
    user: root
    command: ["-Djboss.http.port=${KEYCLOAK_PORT}"]
    expose: 
      - ${KEYCLOAK_PORT}
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_IMPORT: /keycloak-realm.json
    volumes:
      - "./keycloak-dina-starter-realm.json:/keycloak-realm.json"
      - "./dina-keycloak-theme:/opt/jboss/keycloak/themes/dina"
    networks:
      dina:
    labels:
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_HOSTNAME}`)"

  traefik:
    image: traefik:v2.2.0
    command:
      - "--providers.docker=true"
      - "--entrypoints.traefik.address=:9090"
      - "--entrypoints.dockerweb.address=:8080"
      - "--entrypoints.http.address=:80"
      # debug flags - may be commented or removed
      # Traefik dashboard: access localhost:8999 in browser
      - "--api.insecure=true"
      # access logs: use "docker logs --follow [traefik container]"
      - "--accesslog=true"
      # debug logging: enable the traefik.log volume to use these
      # - "--log.filePath=/traefik.log"
      # - "--log.level=DEBUG"
    ports:
      # - "80:80" # Traefik-connected services
      - "8999:9090" # Traefik web UI
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Allow Traefik to log to a local file
      # - ./traefik.log:/traefik.log
    networks:
      dina:
        ipv4_address: ${TRAEFIK_IP}
      default:

  dina-db:
    image: "postgres:10"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

  init-db:
    image: "aafcbicoe/dina-db-init-container:0.2"
    environment:
      POSTGRES_HOST: dina-db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

      DINA_DB: agent collection dina_user object_store seqdb

      MIGRATION_USER_agent: ${AGENT_MIGRATION_USER}
      MIGRATION_USER_PW_agent: ${AGENT_MIGRATION_USER_PW}
      WEB_USER_agent: ${AGENT_WEB_USER}
      WEB_USER_PW_agent: ${AGENT_WEB_USER_PW}

      MIGRATION_USER_collection: ${COLL_MIGRATION_USER}
      MIGRATION_USER_PW_collection: ${COLL_MIGRATION_USER_PW}
      WEB_USER_collection: ${COLL_WEB_USER}
      WEB_USER_PW_collection: ${COLL_WEB_USER_PW}

      MIGRATION_USER_dina_user: ${DINA_USER_MIGRATION_USER}
      MIGRATION_USER_PW_dina_user: ${DINA_USER_MIGRATION_USER_PW}
      WEB_USER_dina_user: ${DINA_USER_WEB_USER}
      WEB_USER_PW_dina_user: ${DINA_USER_WEB_USER_PW}

      MIGRATION_USER_object_store: ${OBJ_STORE_MIGRATION_USER}
      MIGRATION_USER_PW_object_store: ${OBJ_STORE_MIGRATION_USER_PW}
      WEB_USER_object_store: ${OBJ_STORE_WEB_USER}
      WEB_USER_PW_object_store: ${OBJ_STORE_WEB_USER_PW}

      MIGRATION_USER_seqdb: ${SEQDB_MIGRATION_USER}
      MIGRATION_USER_PW_seqdb: ${SEQDB_MIGRATION_USER_PW}
      WEB_USER_seqdb: ${SEQDB_WEB_USER}
      WEB_USER_PW_seqdb: ${SEQDB_WEB_USER_PW}
      PG_EXTENSION_seqdb: pgcrypto

    depends_on:
      - "dina-db"

