version: "3.9"
networks:
  dina:
    ipam:
      config:
        - subnet: ${SUBNET}
services:
  keycloak:
    build:
      context: keycloak/.
    expose: 
      - ${KEYCLOAK_PORT}
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak_db
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: keycloak_user
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
    networks:
      dina:
    labels:
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_HOSTNAME}`)"
    depends_on:
      - keycloak-db

  traefik:
    image: traefik:v2.3.7
    command:
      - "--providers.docker=true"
      - "--entrypoints.traefik.address=:9090"
      - "--entrypoints.dockerweb.address=:8080"
      - "--entrypoints.http.address=:80"
      # debug flags - may be commented or removed
      # Traefik dashboard: access localhost:8999 in browser
      - "--api.insecure=true"
      # access logs: use "docker logs --follow [traefik container]"
      - "--accesslog=true"
      # debug logging: enable the traefik.log volume to use these
      # - "--log.filePath=/traefik.log"
      # - "--log.level=DEBUG"
    ports:
      # - "80:80" # Traefik-connected services
      - "8999:9090" # Traefik web UI
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      # Allow Traefik to log to a local file
      # - ./traefik.log:/traefik.log
    networks:
      dina:
        ipv4_address: ${TRAEFIK_IP}

  dina-db:
    image: "postgis/postgis:12-3.1-alpine"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${POSTGRES_DB}", "-U", "${POSTGRES_USER}" ]
      timeout: 5s
      interval: 10s
      retries: 10
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    networks:
      - dina
    volumes:
      # Over write https://github.com/postgis/docker-postgis/blob/master/10-3.1/Dockerfile#L16
      - ./skipPostGisExtensions.sh:/docker-entrypoint-initdb.d/10_postgis.sh

  keycloak-db:
    image: "postgres:12"
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_PASSWORD: keycloak_user
      POSTGRES_USER: keycloak_user
    networks:
      - dina
    volumes:
      - ./keycloak-data:/var/lib/postgresql/data

  init-db:
    image: "aafcbicoe/dina-db-init-container:0.2"
    environment:
      POSTGRES_HOST: dina-db
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}

      DINA_DB: agent collection dina_user object_store seqdb loan_transaction

      MIGRATION_USER_agent: ${AGENT_MIGRATION_USER}
      MIGRATION_USER_PW_agent: ${AGENT_MIGRATION_USER_PW}
      WEB_USER_agent: ${AGENT_WEB_USER}
      WEB_USER_PW_agent: ${AGENT_WEB_USER_PW}

      MIGRATION_USER_collection: ${COLL_MIGRATION_USER}
      MIGRATION_USER_PW_collection: ${COLL_MIGRATION_USER_PW}
      WEB_USER_collection: ${COLL_WEB_USER}
      WEB_USER_PW_collection: ${COLL_WEB_USER_PW}
      PG_EXTENSION_collection: postgis

      MIGRATION_USER_dina_user: ${DINA_USER_MIGRATION_USER}
      MIGRATION_USER_PW_dina_user: ${DINA_USER_MIGRATION_USER_PW}
      WEB_USER_dina_user: ${DINA_USER_WEB_USER}
      WEB_USER_PW_dina_user: ${DINA_USER_WEB_USER_PW}

      MIGRATION_USER_object_store: ${OBJ_STORE_MIGRATION_USER}
      MIGRATION_USER_PW_object_store: ${OBJ_STORE_MIGRATION_USER_PW}
      WEB_USER_object_store: ${OBJ_STORE_WEB_USER}
      WEB_USER_PW_object_store: ${OBJ_STORE_WEB_USER_PW}

      MIGRATION_USER_seqdb: ${SEQDB_MIGRATION_USER}
      MIGRATION_USER_PW_seqdb: ${SEQDB_MIGRATION_USER_PW}
      WEB_USER_seqdb: ${SEQDB_WEB_USER}
      WEB_USER_PW_seqdb: ${SEQDB_WEB_USER_PW}
      PG_EXTENSION_seqdb: pgcrypto

      MIGRATION_USER_loan_transaction: ${LOAN_TRANSACTION_MIGRATION_USER}
      MIGRATION_USER_PW_loan_transaction: ${LOAN_TRANSACTION_MIGRATION_USER_PW}
      WEB_USER_loan_transaction: ${LOAN_TRANSACTION_WEB_USER}
      WEB_USER_PW_loan_transaction: ${LOAN_TRANSACTION_WEB_USER_PW}
    networks:
      - dina

    depends_on:
      dina-db:
        condition: service_healthy
