services:
  keycloak:
    environment:
      DB_ADDR: keycloak-db:5433 # should match service name and port
      DB_USER: keycloak_user
      DB_PASSWORD: keycloak_user
      DB_DATABASE: keycloak_db
    depends_on:
      - "keycloak-db"

  keycloak-db:
    image: "postgres:12"
    environment:
      POSTGRES_DB: keycloak_db
      POSTGRES_PASSWORD: keycloak_user
      POSTGRES_USER: keycloak_user
    networks:
      - dina
    volumes:
      - ./keycloak-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"