version: "3.7"
services:
  object-store-api:
    environment:
      keycloak.enabled: "true"
      keycloak.auth-server-url: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT}/auth
    networks:
      - dina
    extra_hosts:
      - ${KEYCLOAK_HOSTNAME}:${TRAEFIK_IP}
    labels:
      # maps api.dina.local/objectstore/api/v1/... -> object_store_api/api/v1
      - "traefik.http.middlewares.stripobjectstore.stripprefix.prefixes=${OBJECT_STORE_API_PREFIX}"
      - "traefik.http.routers.objectstoreapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${OBJECT_STORE_API_PREFIX}/`)"
      - "traefik.http.routers.objectstoreapi.middlewares=stripobjectstore@docker"

  object-store-ui:
    build:
      context: ./dina-ui
      dockerfile: objectstore-ui.Dockerfile
    environment:
      KEYCLOAK_CLIENTID: objectstore
      KEYCLOAK_REALM: dina
      KEYCLOAK_PUBLIC_URL: http://${KEYCLOAK_HOSTNAME}:${KEYCLOAK_PORT}/auth
    networks:
      - dina
    ports:
      - "2015:80"
    labels:
      - "traefik.http.routers.ui.rule=Host(`${OBJECT_STORE_UI_HOSTNAME}`)"

  agent-api:
    networks:
      - dina
    labels:
      # Opens http://api.dina.local/agent/api/v1/ module endpoint
      - "traefik.http.middlewares.stripagent.stripprefix.prefixes=${AGENT_API_PREFIX}"
      - "traefik.http.routers.agentapi.rule=Host(`${API_HOSTNAME}`) && PathPrefix(`${AGENT_API_PREFIX}/`)"
      - "traefik.http.routers.agentapi.middlewares=stripagent@docker"
