REVOKE CONNECT ON DATABASE dina_user_test FROM PUBLIC;
REVOKE USAGE, CREATE ON SCHEMA public FROM PUBLIC;

CREATE SCHEMA IF NOT EXISTS dina_user;
REVOKE CREATE ON SCHEMA dina_user FROM PUBLIC;

-- migration user
CREATE ROLE migration_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'test';
GRANT CONNECT ON DATABASE dina_user_test TO migration_user;
GRANT USAGE, CREATE ON SCHEMA dina_user TO migration_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA dina_user GRANT ALL PRIVILEGES ON TABLES TO migration_user;

-- web user
CREATE ROLE web_user NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN PASSWORD 'test';
GRANT CONNECT ON DATABASE dina_user_test TO web_user;
GRANT USAGE ON SCHEMA dina_user TO web_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA dina_user TO web_user;
ALTER DEFAULT PRIVILEGES FOR USER migration_user IN SCHEMA dina_user GRANT SELECT, INSERT, UPDATE, DELETE, REFERENCES ON TABLES TO web_user;
ALTER DEFAULT PRIVILEGES FOR USER migration_user IN SCHEMA dina_user GRANT SELECT, USAGE ON SEQUENCES TO web_user;
