version: "3.9"

# Configuration for the DINA services
x-dev-user-config: &dev-user-config
  SPRING_APPLICATION_JSON: |-
    {
      "keycloak.enabled": false,
      "dev-user": {
        "enabled": true,
        "adminRole": ["dina-admin"],
        "groupRole": {
          "aafc": ["user"],
          "bicoe": ["read-only"]
        }
      }
    }

services:
  # Disable keycloak containers
  keycloak:
    profiles: ["NO_KEYCLOAK"]
  keycloak-db:
    profiles: ["NO_KEYCLOAK"]

  dina-ui:
    environment:
      KEYCLOAK_ENABLED: false
      DEV_USER_ENABLED: true
      DEV_USER_GROUP_ROLE: /aafc/user, /bicoe/read-only, dina-admin

  agent-api:
    environment:
      <<: *dev-user-config

  collection-api:
    environment:
      <<: *dev-user-config

  loan-transaction-api:
    environment:
      <<: *dev-user-config

  dina-user-api:
    environment:
      <<: *dev-user-config

  object-store-api:
    environment:
      <<: *dev-user-config

  seqdb-api:
    environment:
      <<: *dev-user-config

  dina-export-api:
    environment:
      <<: *dev-user-config