apiVersion: apps/v1
kind: Deployment
metadata:
  #namespace: {{ .Values.app.namespace }}
  labels:
    app: {{ .Values.app.name }}
  name: {{ .Values.app.name }}-keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-keycloak
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  template:
    metadata:
      annotations: {}
      #  traefik.enable: "true"
      #  traefik.http.routers.keycloak.rule: Host(``, ``) && PathPrefix(``)
      #  traefik.http.routers.keycloak.tls: "true"
      #  traefik.http.services.keycloak.loadbalancer.server.port: "8080"
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}-keycloak
    spec:
      containers:
        - name: keycloak
          command:
          - /bin/bash
          - -ce
          args:
          - |
            /opt/keycloak/bin/kc.sh start --import-realm
            tail -f /dev/null
          image: quay.io/keycloak/keycloak:20.0.5
          imagePullPolicy: Always
          env:
            - name: KC_DB_PASSWORD
              value: {{ .Values.services.keycloak.environment.KC_DB_PASSWORD}}
            - name: KC_DB_URL_DATABASE
              value: {{ .Values.services.keycloak.environment.KC_DB_URL_DATABASE }}
            - name: KC_DB_URL_HOST
              value: {{ .Values.services.keycloak.environment.KC_DB_URL_HOST }}
            - name: KC_DB_USERNAME
              value: {{ .Values.services.keycloak.environment.KC_DB_USERNAME }}
            - name: KC_HOSTNAME
              value: {{ .Values.services.keycloak.environment.KC_HOSTNAME }}
            - name: KC_HOSTNAME_ADMIN
              value: {{ .Values.services.keycloak.environment.KC_HOSTNAME_ADMIN }}
            - name: KC_PROXY
              value: {{ .Values.services.keycloak.environment.KC_PROXY }}
            - name: KEYCLOAK_ADMIN
              value: {{ .Values.services.keycloak.environment.KEYCLOAK_ADMIN }}
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: {{ .Values.services.keycloak.environment.KEYCLOAK_ADMIN_PASSWORD }}
            - name: KEYCLOAK_IMPORT
              value: data/import/keycloak-dina-starter-realm.json
            - name: KC_HTTP_RELATIVE_PATH
              value: /auth
          ports:
            - name: http
              containerPort: 8080
            - name: https
              containerPort: 8443
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: /auth/realms/master
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          resources:
            requests:
              memory: 2Gi
              cpu: 500m            
            limits:
              memory: 4Gi
              cpu: 1
          volumeMounts:
            - name: keycloak-dina-starter-volume
              mountPath: /opt/keycloak/data/import
            - name: keycloak-theme-volume
              mountPath: /opt/keycloak/themes/dina
            - name: keycloak-scripts
              mountPath: /opt/keycloak/scripts
            - name: certs-volume
              mountPath: /etc/certs
      volumes:
        - name: keycloak-dina-starter-volume
          configMap:
            name: keycloak
        - name: keycloak-scripts
          configMap:
            name: scripts-configmap
        - name: keycloak-theme-volume
          configMap:
            name: keycloak-theme
        - name: certs-volume
          configMap:
            name: certs
status: {}
