apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Values.app.name }}-keycloak-db
  name: {{ .Values.app.name }}-keycloak-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-keycloak-db
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0  
  template:
    metadata:
      annotations: {}
      creationTimestamp: null
      labels:
        app: {{ .Values.app.name }}-keycloak-db
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: {{ .Values.services.keycloakdb.environment.POSTGRES_DB }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.services.keycloakdb.environment.POSTGRES_PASSWORD }}
            - name: POSTGRES_USER
              value: {{ .Values.services.keycloakdb.environment.POSTGRES_USER }}
            - name: PGDATA
              value: /var/lib/postgresql/data
          image: postgres:12
          name: keycloak-db
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }} 
              cpu: {{ .Values.resources.requests.cpu }} 
            limits:
              memory: {{ .Values.resources.limits.memory }} 
              cpu: {{ .Values.resources.limits.cpu }} 
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: keycloak-db-claim
      volumes:
        - name: keycloak-db-claim
          persistentVolumeClaim:
            claimName: keycloak-db-claim
status: {}
