apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-configmap
data:
{{ (.Files.Glob "config/scripts/skipPostGisExtensions.sh").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
data:
{{ (.Files.Glob "config/keycloak/keycloak-dina-starter-realm.json").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-theme
data:
{{ (.Files.Glob "config/dina-keycloak-theme/").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-data
data:
{{ (.Files.Glob "config/keycloak-data/").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certs
data:
{{ (.Files.Glob "config/certs").AsConfig | indent 2 }}