/*!
 * DINA UI Instance Banners for the Welcome Page
 * 
 * This script fetches instance information from the API and displays a banner if the instance 
 * matches any of the configured banners.
 * 
 * This script was AI assisted.
 */

/**
 * INSTANCE_BANNERS is a list of banner definitions.
 *
 * A banner is shown only when both instanceMode and instanceName match
 * the values returned by /api/instance.json.
 * 
 * Each banner must define a type (info | success | warning | danger).
 * 
 * Titles and messages must be provided in both English and French.
 * 
 * If the API is unavailable or no banner matches, nothing is displayed.
 */
const INSTANCE_BANNERS = [
  {
    match: {
      instanceMode: "TEST",
      instanceName: "GRDI"
    },
    banner: {
      type: "warning",
      titleEn: "TEST ENVIRONMENT",
      messageEn:
        "This is the DINA test instance. The demo account has write access so users can explore and experiment freely. Data created in this environment is temporary and is not persisted.",
      titleFr: "ENVIRONNEMENT DE TEST",
      messageFr:
        "Ceci est l’instance de test de DINA. Le compte de démonstration dispose d’un accès en écriture afin de permettre l’exploration et les essais. Les données créées dans cet environnement sont temporaires et ne sont pas conservées."
    }
  }
];

/**
 * Endpoint to fetch instance information for banner matching. Cache is disabled to ensure
 * the most up-to-date information is used on each page load.
 * 
 * This endpoint is expected to return a JSON object with at least the following properties:
 * - instance-mode: string
 * - instance-name: string
 * 
 * This is being generated by the Caddyfile in the Dina UI.
 */
const ENDPOINT = "/api/instance.json";

/**
 * IDs of the containers where banners will be rendered. These should match the IDs used in
 * welcome-bienvenue.html.
 */
const EN_CONTAINER_ID = "instance-banner-en";
const FR_CONTAINER_ID = "instance-banner-fr";

(function () {
  fetch(ENDPOINT, { cache: "no-store" })
    .then(response => {
      if (!response.ok) return;
      return response.json();
    })
    .then(data => {
      const bannerConfig = findMatchingBanner(data);
      if (bannerConfig) {
        renderEnglishBanner(bannerConfig);
        renderFrenchBanner(bannerConfig);
      }
    })
    .catch(() => {
      console.warn("Could not fetch instance information for banner display.");
    });

  function findMatchingBanner(instanceData) {
    return INSTANCE_BANNERS.find(entry =>
      entry.match.instanceMode === instanceData["instance-mode"] &&
      entry.match.instanceName === instanceData["instance-name"]
    );
  }

  function renderEnglishBanner(config) {
    renderBanner(
      EN_CONTAINER_ID,
      config.banner.type,
      config.banner.titleEn,
      config.banner.messageEn,
      "en"
    );
  }

  function renderFrenchBanner(config) {
    renderBanner(
      FR_CONTAINER_ID,
      config.banner.type,
      config.banner.titleFr,
      config.banner.messageFr,
      "fr"
    );
  }

  function renderBanner(containerId, type, title, message, lang) {
    const container = document.getElementById(containerId);
    if (!container) return;

    container.innerHTML = `
      <section class="alert alert-${type}" role="alert" lang="${lang}">
        <h3>${escapeHtml(title)}</h3>
        <p>${escapeHtml(message)}</p>
      </section>
    `;
  }

  function escapeHtml(str) {
    return String(str).replace(/[&<>"']/g, c => ({
      "&": "&amp;",
      "<": "&lt;",
      ">": "&gt;",
      '"': "&quot;",
      "'": "&#39;"
    }[c]));
  }
})();
