apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-configmap
data:
{{ (.Files.Glob "config/scripts/skipPostGisExtensions.sh").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
data:
{{ (.Files.Glob "config/keycloak/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-theme
data:
  {{- $files := .Files }}
  {{- range $key, $value := .Files }}
  {{- if hasPrefix "config/theme/" $key }} 
  {{ $key | trimPrefix "config/theme/" }}: {{ $files.Get $key | quote }} {{/* adapt $key as desired */}}
  {{- end }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-data
data:
{{ (.Files.Glob "config/keycloak-data/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-data
data:
{{ (.Files.Glob "./minio-data/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certs
data:
{{ (.Files.Glob "config/certs/*").AsConfig | indent 2 }}