global:
  scrape_interval:     30s
  evaluation_interval: 30s
  # scrape_timeout default 10s

scrape_configs:
  - job_name: 'DINA scrape'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['collection-api:8080']
