{{- /* Define the list of secrets and their corresponding existing value settings */ -}}
{{- $secretConfigs := list
  (dict "name" "dina-db-secret" "val" .Values.global.environment.config.dina_db.db_password)
  (dict "name" "keycloak-db-secret" "val" .Values.global.environment.config.keycloak.db_password)
  (dict "name" "keycloak-admin-secret" "val" .Values.global.environment.config.keycloak.keycloak_admin_password)
  (dict "name" "collectionapi-datasource-secret" "val" .Values.services.collectionapi.environment.spring.datasource.password)
  (dict "name" "collectionapi-liquibase-secret" "val" .Values.services.collectionapi.environment.spring.liquibase.password)
  (dict "name" "objectstoreapi-datasource-secret" "val" .Values.services.objectstoreapi.environment.spring.datasource.password)
  (dict "name" "objectstoreapi-liquibase-secret" "val" .Values.services.objectstoreapi.environment.spring.liquibase.password)
  (dict "name" "dinauserapi-liquibase-secret" "val" .Values.services.dinauserapi.environment.spring.liquibase.password)
  (dict "name" "dinauserapi-datasource-secret" "val" .Values.services.dinauserapi.environment.spring.datasource.password)
  (dict "name" "loantransactionapi-datasource-secret" "val" .Values.services.loantransactionapi.environment.spring.datasource.password)
  (dict "name" "loantransactionapi-liquibase-secret" "val" .Values.services.loantransactionapi.environment.spring.liquibase.password)
  (dict "name" "agentapi-datasource-secret" "val" .Values.services.agentapi.environment.spring.datasource.password)
  (dict "name" "agentapi-liquibase-secret" "val" .Values.services.agentapi.environment.spring.liquibase.password)
  (dict "name" "dinaexportapi-datasource-secret" "val" .Values.services.dinaexportapi.environment.spring.datasource.password)
  (dict "name" "dinaexportapi-liquibase-secret" "val" .Values.services.dinaexportapi.environment.spring.liquibase.password)
  (dict "name" "seqdbapi-datasource-secret" "val" .Values.services.seqdbapi.environment.spring.datasource.password)
  (dict "name" "seqdbapi-liquibase-secret" "val" .Values.services.seqdbapi.environment.spring.liquibase.password)
  (dict "name" "elasticsearch-secret" "val" .Values.global.environment.config.elasticsearch.password)
}}

{{- $namespace := .Release.Namespace -}}

{{- range $index, $secret := $secretConfigs }}
{{- $existingSecret := (lookup "v1" "Secret" $namespace $secret.name) -}}
{{- /* Only create the secret if the value isn't provided in helm values AND it doesn't already exist in the cluster */ -}}
{{- if and (not $secret.val) (not $existingSecret) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name | quote }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
  {{- /* Note: Lookup returned nothing, generate new password */}}
  password: {{ randAlphaNum 32 | b64enc | quote }}
{{- end }}
{{- end }}
