{{- if .Values.global.environment.isOpenShift }}
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
type: Opaque
data:
  git-username: {{ .Values.global.environment.git.user | default "" | b64enc }}
  git-token: {{ .Values.global.environment.git.password | default "" | b64enc }}
  git-host: {{ .Values.global.environment.git.host | default "" | b64enc }}
  git-repo: {{ .Values.global.environment.git.repo | default "" | b64enc }}
  git-project: {{ .Values.global.environment.git.project | default "" | b64enc }}
{{- end }}