{{- if .Values.global.environment.isOpenShift }}
apiVersion: v1
kind: Secret
metadata:
  name: git-secret
type: Opaque
data:
  git-username: {{ .Values.global.environment.git.user | b64enc }}
  git-token: {{ .Values.global.environment.git.password | b64enc }}
  git-host: {{ .Values.global.environment.git.host | b64enc }}
  git-repo: {{ .Values.global.environment.git.repo | b64enc }}
  git-project: {{ .Values.global.environment.git.project | b64enc }}
{{- end }}