{{- if .Values.global.environment.isOpenShift }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-db-restore-cm
  annotations:
    "helm.sh/hook": pre-install
spec:
  template:
    spec:
      containers:
      - name: create-configmap
        image: busybox
        command:
          - sh
          - -c
          - |
            FILE_CONTENT=$(cat {{ .Values.global.environment.config.dina_db.db_dump_file_name }} | base64)
            kubectl create configmap pg-restore-cm --from-literal=sql_dump.sql=$FILE_CONTENT
      restartPolicy: OnFailure
{{- end }}
