{{- if or .Values.services.initdb.environment.RESTORE_DB .Values.services.initdb.environment.RESET_USERS }}
apiVersion: batch/v1
kind: Job
metadata:
  name: db-restore-job
spec:
  template:
    spec:
      initContainers:
        - name: check-db
          image: {{ .Values.services.initdb.image }}
          command:
            - sh
            - -c
            - until pg_isready -h {{ tpl .Values.services.initdb.environment.POSTGRES_HOST . }}; do echo waiting for database; sleep 10; done;
          resources:
            requests:
              memory: {{ .Values.resources.initcontainers.requests.memory }}
              cpu: {{ .Values.resources.initcontainers.requests.cpu }}            
            limits:
              memory: {{ .Values.resources.initcontainers.limits.memory }} 
              cpu: {{ .Values.resources.initcontainers.limits.cpu }}
        - name: mount-db-restore
          image: alpine/git
          command:
            - sh
            - -c
            - |
              cd /mnt/data
              git clone https://$(cat /mnt/secrets/git-host)/$(cat /mnt/secrets/git-repo)/$(cat /mnt/secrets/git-project).git
              cd $(cat /mnt/secrets/git-project)
              git lfs pull
              sql_file=$(find . -name "*.sql" -print -quit)
              if [ -n "$sql_file" ]; then
                cat "$sql_file" | base64 > /mnt/data/sql_dump.sql.b64
              else
                echo "No .sql file found."
              fi
          volumeMounts:
            - name: emptydir-volume
              mountPath: /mnt/data
            - name: git-secret-volume
              mountPath: /mnt/secrets
              readOnly: true
      containers:
        - name: restore-db
          image: {{ .Values.services.initdb.image }}
          env:
          # Database Connection:
          - name: POSTGRES_HOST
            value: {{ tpl .Values.services.initdb.environment.POSTGRES_HOST . }}
          - name: POSTGRES_DB
            value: {{ tpl .Values.services.initdb.environment.POSTGRES_DB . }}
          - name: POSTGRES_USER
            value: {{ tpl .Values.services.initdb.environment.POSTGRES_USER . }}
          - name: POSTGRES_PASSWORD
            {{- if not .Values.services.initdb.environment.POSTGRES_PASSWORD }}
            valueFrom:
              secretKeyRef:
                name: dina-db-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.environment.POSTGRES_PASSWORD . }}
            {{- end }}

          # Database Restore
          - name: RESTORE_DB
            value: {{ .Values.services.initdb.environment.RESTORE_DB }}
          - name: DB_DUMP_FILE_PATH
            value: {{ .Values.services.initdb.environment.DB_DUMP_FILE_PATH }}

          # Reset users / Generate Databases
          - name: RESET_USERS
            value: {{ .Values.services.initdb.environment.RESET_USERS }}
          - name: DINA_DB
            value: {{ .Values.services.initdb.environment.DINA_DB }}
          - name: DB_USER
            value: {{ .Values.services.initdb.environment.DB_USER }}
          - name: DB_PASSWORD
            value: {{ .Values.services.initdb.environment.DB_PASSWORD }}

          # Agent API (Defined in Values.services.initdb.config.agentapi)
          - name: MIGRATION_USER_agent
            value: {{ tpl .Values.services.initdb.config.agentapi.spring.liquibase.username . }}
          - name: MIGRATION_USER_PW_agent
            {{- if not .Values.services.initdb.config.agentapi.spring.liquibase.password }}
            valueFrom:
              secretKeyRef:
                name: agentapi-liquibase-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.agentapi.spring.liquibase.password . }}
            {{- end }}
          - name: WEB_USER_agent
            value: {{ tpl .Values.services.initdb.config.agentapi.spring.datasource.username . }}
          - name: WEB_USER_PW_agent
            {{- if not .Values.services.initdb.config.agentapi.spring.datasource.password }}
            valueFrom:
              secretKeyRef:
                name: agentapi-datasource-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.agentapi.spring.datasource.password . }}
            {{- end }}

          # Collection API (Defined in Values.services.initdb.config.collectionapi)
          - name: MIGRATION_USER_collection
            value: {{ tpl .Values.services.initdb.config.collectionapi.spring.liquibase.username . }}
          - name: MIGRATION_USER_PW_collection
            {{- if not .Values.services.initdb.config.collectionapi.spring.liquibase.password }}
            valueFrom:
              secretKeyRef:
                name: collection-liquibase-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.collectionapi.spring.liquibase.password . }}
            {{- end }}
          - name: WEB_USER_collection
            value: {{ tpl .Values.services.initdb.config.collectionapi.spring.datasource.username . }}
          - name: WEB_USER_PW_collection
            {{- if not .Values.services.initdb.config.collectionapi.spring.datasource.password }}
            valueFrom:
              secretKeyRef:
                name: collection-datasource-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.collectionapi.spring.datasource.password . }}
            {{- end }}
          - name: PG_EXTENSION_collection
            value: {{ .Values.services.initdb.config.collectionapi.PG_EXTENSION_collection }}

          # Dina User API (Defined in Values.services.initdb.config.dinauserapi)
          - name: MIGRATION_USER_dina_user
            value: {{ tpl .Values.services.initdb.config.dinauserapi.spring.liquibase.username . }}
          - name: MIGRATION_USER_PW_dina_user
            {{- if not .Values.services.initdb.config.dinauserapi.spring.liquibase.password }}
            valueFrom:
              secretKeyRef:
                name: dinauserapi-liquibase-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.dinauserapi.spring.liquibase.password . }}
            {{- end }}
          - name: WEB_USER_dina_user
            value: {{ tpl .Values.services.initdb.config.dinauserapi.spring.datasource.username . }}
          - name: WEB_USER_PW_dina_user
            {{- if not .Values.services.initdb.config.dinauserapi.spring.datasource.password }}
            valueFrom:
              secretKeyRef:
                name: dinauserapi-datasource-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.dinauserapi.spring.datasource.password . }}
            {{- end }}
          
          # DINA Export API (Defined in Values.services.initdb.config.dinaexportapi)
          - name: MIGRATION_USER_export
            value: {{ tpl .Values.services.initdb.config.dinaexportapi.spring.liquibase.username . }}
          - name: MIGRATION_USER_PW_export
            {{- if not .Values.services.initdb.config.dinaexportapi.spring.liquibase.password }}
            valueFrom:
              secretKeyRef:
                name: dinaexportapi-liquibase-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.dinaexportapi.spring.liquibase.password . }}
            {{- end }}
          - name: WEB_USER_export
            value: {{ tpl .Values.services.initdb.config.dinaexportapi.spring.datasource.username . }}
          - name: WEB_USER_PW_export
            {{- if not .Values.services.initdb.config.dinaexportapi.spring.datasource.password }}
            valueFrom:
              secretKeyRef:
                name: dinaexportapi-datasource-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.dinaexportapi.spring.datasource.password . }}
            {{- end }}

          # Loan and Transaction API (Defined in Values.services.initdb.config.loantransactionapi)
          - name: MIGRATION_USER_loan_transaction
            value: {{ tpl .Values.services.initdb.config.loantransactionapi.spring.liquibase.username . }}
          - name: MIGRATION_USER_PW_loan_transaction
            {{- if not .Values.services.initdb.config.loantransactionapi.spring.liquibase.password }}
            valueFrom:
              secretKeyRef:
                name: loantransactionapi-liquibase-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.loantransactionapi.spring.liquibase.password . }}
            {{- end }}
          - name: WEB_USER_loan_transaction
            value: {{ tpl .Values.services.initdb.config.loantransactionapi.spring.datasource.username . }}
          - name: WEB_USER_PW_loan_transaction
            {{- if not .Values.services.initdb.config.loantransactionapi.spring.datasource.password }}
            valueFrom:
              secretKeyRef:
                name: loantransactionapi-datasource-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.loantransactionapi.spring.datasource.password . }}
            {{- end }}

          # Object Store API (Defined in Values.services.initdb.config.objectstoreapi)
          - name: MIGRATION_USER_object_store
            value: {{ tpl .Values.services.initdb.config.objectstoreapi.spring.liquibase.username . }}
          - name: MIGRATION_USER_PW_object_store
            {{- if not .Values.services.initdb.config.objectstoreapi.spring.liquibase.password }}
            valueFrom:
              secretKeyRef:
                name: objectstore-liquibase-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.objectstoreapi.spring.liquibase.password . }}
            {{- end }}
          - name: WEB_USER_object_store
            value: {{ tpl .Values.services.initdb.config.objectstoreapi.spring.datasource.username . }}
          - name: WEB_USER_PW_object_store
            {{- if not .Values.services.initdb.config.objectstoreapi.spring.datasource.password }}
            valueFrom:
              secretKeyRef:
                name: objectstore-datasource-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.objectstoreapi.spring.datasource.password . }}
            {{- end }}

          # SeqDB API (Defined in Values.services.initdb.config.seqdbapi)
          - name: MIGRATION_USER_seqdb
            value: {{ tpl .Values.services.initdb.config.seqdbapi.spring.liquibase.username . }}
          - name: MIGRATION_USER_PW_seqdb
            {{- if not .Values.services.initdb.config.seqdbapi.spring.liquibase.password }}
            valueFrom:
              secretKeyRef:
                name: seqdbapi-liquibase-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.seqdbapi.spring.liquibase.password . }}
            {{- end }}
          - name: WEB_USER_seqdb
            value: {{ tpl .Values.services.initdb.config.seqdbapi.spring.datasource.username . }}
          - name: WEB_USER_PW_seqdb
            {{- if not .Values.services.initdb.config.seqdbapi.spring.datasource.password }}
            valueFrom:
              secretKeyRef:
                name: seqdbapi-datasource-secret
                key: password
            {{- else }}
            value: {{ tpl .Values.services.initdb.config.seqdbapi.spring.datasource.password . }}
            {{- end }}
          - name: PG_EXTENSION_seqdb
            value: {{ .Values.services.initdb.config.seqdbapi.PG_EXTENSION_collection }}
          volumeMounts:
            - name: emptydir-volume
              mountPath: /mnt/data/
          resources:
            requests:
              memory: {{ .Values.resources.initcontainers.requests.memory }}
              cpu: {{ .Values.resources.initcontainers.requests.cpu }}            
            limits:
              memory: {{ .Values.resources.initcontainers.limits.memory }} 
              cpu: {{ .Values.resources.initcontainers.limits.cpu }}
      volumes:
        - name: emptydir-volume
          emptyDir: {}
        - name: git-secret-volume
          secret:
            secretName: git-secret
      restartPolicy: Never
{{- end }}
