apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-keycloak-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2500m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 12k
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - keycloak.dina.local
    secretName: keycloak.dina.local-tls
  rules:
    - host: {{ .Values.services.keycloak.environment.KC_HOSTNAME }}
      http:
        paths:
        - path: "/auth"
          pathType: Prefix
          backend:
            service:
              name: keycloak-service
              port:
                number: 8080
    - host: {{ .Values.services.keycloak.environment.KC_HOSTNAME_ADMIN }}
      http:
        paths:
        - path: "/auth"
          pathType: Prefix
          backend:
            service:
              name: keycloak-service
              port:
                number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-collection-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2500m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 12k
    nginx.ingress.kubernetes.io/rewrite-target: /api/v1/$1
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.global.endpoints.api }}
      http:
        paths:
        - path: "/collection/(.*)"
          pathType: Prefix
          backend:
            service:
              name: collection-api-service
              port:
                number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-dina-ui-ingress
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 2500m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 12k
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - dina.local
    secretName: keycloak.dina.local-tls
  rules:
    - host: {{ .Values.services.keycloak.environment.KC_HOSTNAME }}
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: dina-ui-service
              port:
                number: 8080
                