# Default values for dina-helm-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  environment:
    isOpenShift: true
    storageClass: ocs-external-storagecluster-ceph-rbd
    securityContext:
      enabled: false
resources:
  general:
    limits:
      memory: 2Gi
      cpu: 1
    requests:
      cpu: 400m
      memory: 1Gi
  apis:
    limits:
      memory: 512Mi
      cpu: 160m
    requests:
      cpu: 80m
      memory: 256Mi
  initcontainers:
    limits:
      memory: 128Mi
      cpu: 20m
    requests:
      cpu: 10m
      memory: 64Mi
      
