# Default values for dina-helm-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
app:
  name: dina-helm
global:
  environment:
    config:
      dina_db:
        label: dina-db
        service: dina-db-service
        db_name: dina
        db_password: 
        db_user: pguser
      keycloak: 
        label: keycloak
        service: keycloak-service
        db_name: keycloak_db
        db_password: 
        db_user: keycloak_user
        keycloak_admin: admin
        keycloak_admin_password: admin
      collection_api:
        label: collection-api
        service: collection-api-service
        datasource_password: 
        datasource_user: web_user_coll
        liquibase_user: migration_user_coll
        liquibase_password: 
      dina_ui: 
        label: dina-ui
        service: dina-ui-service
    keycloak:
      enabled: true
      auth_server_url: "http://{{ .Values.global.environment.config.keycloak.service }}:8080/auth"
  endpoints:
    api: api.dina.local
    ui: dina.local
    keycloak: keycloak.dina.local
services:
  initdb:
    image: aafcbicoe/dina-db-init-container:0.3
    pullPolicy: IfNotPresent
    environment:
      POSTGRES_DB: "{{ .Values.global.environment.config.dina_db.db_name }}"
      POSTGRES_PASSWORD: "{{ .Values.global.environment.config.dina_db.db_password }}"
      POSTGRES_USER: "{{ .Values.global.environment.config.dina_db.db_user }}"
      POSTGRES_HOST: "{{ .Values.global.environment.config.dina_db.service }}"
    config:
      collectionapi:
        DINA_DB: collection
        spring:
          datasource:
            username: "{{ .Values.global.environment.config.collection_api.datasource_user }}"
            password: "{{ .Values.global.environment.config.collection_api.datasource_password }}"
          liquibase:
            user: "{{ .Values.global.environment.config.collection_api.liquibase_user }}"
            password: "{{ .Values.global.environment.config.collection_api.liquibase_password }}"
        actuator:
          allowedIP: prometheus
        PG_EXTENSION_collection: postgis
  collectionapi:
    image: aafcbicoe/natural-history-collection-api:0.80
    pullPolicy: IfNotPresent
    environment:
      spring:
        datasource:
          url: jdbc:postgresql://{{ .Values.global.environment.config.dina_db.service }}/collection?currentSchema=collection
      actuator:
        allowedIP: prometheus
    resources:
      limits:
        memory: 1Gi
        cpu: 1
      requests:
        cpu: 80m
        memory: 768Mi
  dinaui:
    image: aafcbicoe/dina-ui:0.135.0
    environment:
      KEYCLOAK_CLIENTID: dina-public
      KEYCLOAK_REALM: dina
      KEYCLOAK_PUBLIC_URL: https://{{ .Values.global.endpoints.ui }}/auth
      OBJECTSTORE_API_ADDRESS: object-store-api:8080
      AGENT_API_ADDRESS: agent-api:8080
      SEQDB_API_ADDRESS: seqdb-api:8080
      COLLECTION_API_ADDRESS: collection-api-service:8080
      USER_API_ADDRESS: dina-user-api:8080
      SEARCH_API_ADDRESS: search-ws:8085
      LOAN_TRANSACTION_API_ADDRESS: loan-transaction-api:8080
      REPORT_LABEL_API_ADDRESS: dina-export-api:8080
      INSTANCE_MODE: developer
  keycloak:
    pullPolicy: IfNotPresent
    image: "quay.io/keycloak/keycloak:20.0.5"
    environment:
      KC_DB_PASSWORD: "{{ .Values.global.environment.config.keycloak.db_password }}"
      KEYCLOAK_ADMIN: "{{ .Values.global.environment.config.keycloak.keycloak_admin }}"
      KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.global.environment.config.keycloak.keycloak_admin_password }}"
      KC_DB_URL_HOST: "{{ .Values.global.environment.config.dina_db.service }}"
      KC_DB_URL_DATABASE: "{{ .Values.global.environment.config.dina_db.db_name }}"
      KC_DB_USERNAME: "{{ .Values.global.environment.config.keycloak.db_user }}"
      KC_HOSTNAME: "{{ .Values.global.endpoints.ui }}"
      KC_HOSTNAME_ADMIN: "{{ .Values.global.endpoints.keycloak }}"
      KC_PROXY: edge
  dinadb:
    image: "postgis/postgis:12-3.1-alpine"
    environment:
      POSTGRES_DB: "{{ .Values.global.environment.config.keycloak.db_name }}"
      DB_USER: "{{ .Values.global.environment.config.keycloak.db_user }}"
      DB_PASSWORD: "{{ .Values.global.environment.config.keycloak.db_password }}"
      USE_V2: "true"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  tls: true
  className: ""

  hosts:
    - host: dina.local
      paths:
        - path: /
          pathType: Prefix
podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources:
  limits:
    memory: 256Mi
    cpu: 20m
  requests:
    cpu: 10m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
