# Default values for dina-helm-test.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
app:
  name: dina-helm
global:
  environment:
    config:
      dina_db:
        label: dina-db
        service: dina-db-service
        db_name: dina
        db_password: 
        db_user: pguser
      keycloak: 
        label: keycloak
        service: keycloak-service
        db_name: keycloak_db
        db_password: 
        db_user: keycloak_user
        keycloak_admin: admin
        keycloak_admin_password: admin
      collection_api:
        label: collection-api
        service: collection-api-service
        datasource_password: 
        datasource_user: web_user_coll
        liquibase_user: migration_user_coll
        liquibase_password: 
      dina_ui: 
        label: dina-ui
        service: dina-ui-service
      search_cli:
        label: search-cli
        username: cnc-su
        password:
        service: searchcli-service
      search_ws:
        label: search-ws
        service: searchws-service
      elasticsearch:
        label: elasticsearch-dina
        service: elasticsearch-service
      rabbitmq:
        label: rabbitmq-dina
        service: rabbitmq-dina-service
    keycloak:
      client_id: dina-public
      realm: dina
      enabled: true
      auth_server_url: http://{{ .Values.global.environment.config.keycloak.service }}:8080/auth
  endpoints:
    api: api.dina.local
    ui: dina.local
    keycloak: keycloak.dina.local
    elasticsearch: elasticsearch.dina.localhost
services:
  initdb:
    image: aafcbicoe/dina-db-init-container:0.3
    pullPolicy: IfNotPresent
    environment:
      POSTGRES_DB: "{{ .Values.global.environment.config.dina_db.db_name }}"
      POSTGRES_PASSWORD: "{{ .Values.global.environment.config.dina_db.db_password }}"
      POSTGRES_USER: "{{ .Values.global.environment.config.dina_db.db_user }}"
      POSTGRES_HOST: "{{ .Values.global.environment.config.dina_db.service }}"
    config:
      collectionapi:
        DINA_DB: collection
        spring:
          datasource:
            username: "{{ .Values.global.environment.config.collection_api.datasource_user }}"
            password: "{{ .Values.global.environment.config.collection_api.datasource_password }}"
          liquibase:
            user: "{{ .Values.global.environment.config.collection_api.liquibase_user }}"
            password: "{{ .Values.global.environment.config.collection_api.liquibase_password }}"
        actuator:
          allowedIP: prometheus
        PG_EXTENSION_collection: postgis
  collectionapi:
    image: aafcbicoe/natural-history-collection-api:0.80
    pullPolicy: IfNotPresent
    environment:
      rabbitmq:
        host: "{{ .Values.global.environment.config.rabbitmq.service }}"
      messaging:
        isProducer: true
      spring:
        datasource:
          url: jdbc:postgresql://{{ .Values.global.environment.config.dina_db.service }}/collection?currentSchema=collection
      actuator:
        allowedIP: prometheus
    resources:
      limits:
        memory: 1Gi
        cpu: 1
      requests:
        cpu: 80m
        memory: 768Mi
  dinaui:
    image: aafcbicoe/dina-ui:0.135.0
    environment:
      KEYCLOAK_CLIENTID: "{{ .Values.global.environment.keycloak.client_id }}"
      KEYCLOAK_REALM: "{{ .Values.global.environment.keycloak.realm }}"
      KEYCLOAK_PUBLIC_URL: https://{{ .Values.global.endpoints.ui }}/auth
      OBJECTSTORE_API_ADDRESS: object-store-api:8080
      AGENT_API_ADDRESS: agent-api:8080
      SEQDB_API_ADDRESS: seqdb-api:8080
      COLLECTION_API_ADDRESS: "{{ .Values.global.environment.config.collection_api.service }}:8080"
      USER_API_ADDRESS: dina-user-api:8080
      SEARCH_API_ADDRESS: "{{ .Values.global.environment.config.search_ws.service }}:8085"
      LOAN_TRANSACTION_API_ADDRESS: loan-transaction-api:8080
      REPORT_LABEL_API_ADDRESS: dina-export-api:8080
      INSTANCE_MODE: developer
  keycloak:
    pullPolicy: IfNotPresent
    image: "quay.io/keycloak/keycloak:20.0.5"
    environment:
      KC_DB_PASSWORD: "{{ .Values.global.environment.config.keycloak.db_password }}"
      KEYCLOAK_ADMIN: "{{ .Values.global.environment.config.keycloak.keycloak_admin }}"
      KEYCLOAK_ADMIN_PASSWORD: "{{ .Values.global.environment.config.keycloak.keycloak_admin_password }}"
      KC_DB_URL_HOST: "{{ .Values.global.environment.config.dina_db.service }}"
      KC_DB_URL_DATABASE: "{{ .Values.global.environment.config.dina_db.db_name }}"
      KC_DB_USERNAME: "{{ .Values.global.environment.config.keycloak.db_user }}"
      KC_HOSTNAME: "{{ .Values.global.endpoints.ui }}"
      KC_HOSTNAME_ADMIN: "{{ .Values.global.endpoints.keycloak }}"
      KC_PROXY: edge
  elasticsearchdina:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    #image: elasticsearch_icu:7.17.10
    environment:
      xpack:
        security:
          enabled: false
      discovery:
        type: single-node
      action:
        auto_create_index: false
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
  elasticconfigurator:
    image: aafcbicoe/es-init-container:0.6
    environment:
      ELASTIC_SERVER_URL: http://elasticsearch-service:9200
      INDEX_CREATE_CMD: ./create-index.sh
      DINA_INDEX_DECLARATIONS: AGENT MATERIAL_SAMPLE STORAGE OBJECT_STORE TRANSACTION
      DINA_AGENT_INDEX_NAME: dina_agent_index
      DINA_AGENT_INDEX_SETTINGS_FILE: /usr/share/elastic-configurator/settings/agent-index/dina_agent_index_settings.json
      DINA_MATERIAL_SAMPLE_INDEX_NAME: dina_material_sample_index
      DINA_MATERIAL_SAMPLE_INDEX_SETTINGS_FILE: /usr/share/elastic-configurator/settings/collection-index/dina_material_sample_index_settings.json
      DINA_STORAGE_INDEX_NAME: dina_storage_index
      DINA_STORAGE_INDEX_SETTINGS_FILE: /usr/share/elastic-configurator/settings/storage-index/dina_storage_index_settings.json
      DINA_OBJECT_STORE_INDEX_NAME: dina_storage_index
      DINA_OBJECT_STORE_INDEX_SETTINGS_FILE: /usr/share/elastic-configurator/settings/object-store-index/object_store_index_settings.json
      DINA_TRANSACTION_INDEX_NAME: dina_loan_transaction_index
      DINA_TRANSACTION_INDEX_SETTINGS_FILE: /usr/share/elastic-configurator/settings/dina_loan_transaction_index_settings.json
  dinadb:
    image: "postgis/postgis:12-3.1-alpine"
    environment:
      POSTGRES_DB: "{{ .Values.global.environment.config.keycloak.db_name }}"
      DB_USER: "{{ .Values.global.environment.config.keycloak.db_user }}"
      DB_PASSWORD: "{{ .Values.global.environment.config.keycloak.db_password }}"
      USE_V2: "true"
  searchcli:
    image: aafcbicoe/dina-search-cli:0.26
    environment:
      keycloak:
        auth_server_url: "{{ .Values.global.environment.keycloak.auth_server_url }}"
        client_id: "{{ .Values.global.environment.keycloak.client_id }}"
        username: "{{ .Values.global.environment.config.search_cli.username }}"
        password: "{{ .Values.global.environment.config.search_cli.password }}"
      ELASTICSEARCH_URL: "{{ .Values.global.environment.config.elasticsearch.service }}"
      MATERIAL_SAMPLE_URL: http://{{ .Values.global.environment.config.elasticsearch.service }}:8080/api/v1/material-sample
      METADATA_URL: http://object-store-api:8080/api/v1/metadata
      ORGANIZATION_URL: http://agent-api:8080/api/v1/organization
      PERSON_URL: http://agent-api:8080/api/v1/person
      STORAGE_UNIT_URL: http://{{ .Values.global.environment.config.collection_api.service }}:8080/api/v1/storage-unit
      LOAN_TRANSACTION_URL: http://loan-transaction-api:8080/api/v1/transaction
      RABBITMQ_HOSTNAME: "{{ .Values.global.environment.config.rabbitmq.service }}"
      IS_MESSAGE_CONSUMER: true
      IS_MESSAGE_PRODUCER: true
  searchws:
    image: aafcbicoe/dina-search-ws:0.26
    environment:
      elasticsearch:
        host: "{{ .Values.global.environment.config.elasticsearch.service }}"
  rabbitmq:
    image: rabbitmq:3.9.29-management-alpine

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

ingress:
  enabled: true
  tls: true
  className: ""

  hosts:
    - host: dina.local
      paths:
        - path: /
          pathType: Prefix
podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

resources:
  general:
    limits:
      memory: 256Mi
      cpu: 20m
    requests:
      cpu: 10m
      memory: 128Mi
  apis:
    limits:
      memory: 1Gi
      cpu: 1
    requests:
      cpu: 80m
      memory: 768Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
