= API Endpoint Testing

== Applications

While any API client can be used, Bruno is our recommended API client and requires no 3rd party accounts.

Bruno can be downloaded from: https://www.usebruno.com/downloads

Once downloaded, you can open the DINA collection of API endpoints by going to `File` > `Open collection` > Navigate to dina-local-deployment/api-client/DINA-API and open that folder.

You will also need to select the environment variables for the instance you want to connect to, for local dina development you would select `DINA Local`. The dropdown at the top right of the screen lets you change the environment variables.

For local development, you will need to open the Bruno preferences (`CTRL` + `,`), Under the General tab, you will see an option for "Use custom CA certificate", make sure this is checked on. Click the "Select file" option and navigate to `/etc/ssl/certs/ca-certificates.crt`. (Be sure that you have ran the Local Certificate steps in order for the dina local certificates to be inside of the `ca-certificates.crt` file)

Please note that bruno is still under active development.

== Authentication

If using the Bruno API client with our collection loaded, the Authentication settings will be automatically loaded in.

Click the gear icon located at the top right of the screen. Then go to the `Auth` where you can click the "Get Access Token". Currently you need to do this each time to generate the token but probably in the future this will happen automatically when the token has expired. Each request will need to use the inherit authentication option.

In other API clients, you can setup the authentication using these settings:

.Authentication Settings
|===
|Setting |Value

|Authentication Type
|OAuth 2.0

|Grant Type
|Authorization Code

|Authorization URL / Auth URL
|https://dina.local/auth/realms/dina/protocol/openid-connect/auth

|Access Token URL
|https://dina.local/auth/realms/dina/protocol/openid-connect/token

|Client ID
|dina-public

|Redirect URL / Callback URL
|https://dina.local

|Scope
|openid
|===

Then when sending the request, you should see a popup which will let you login to the DINA application.

== Script - Post Response

[source,shell]
----
// Used to pass the oauth2 token generated to the headers.
var token = res.body.access_token;
if (token) {
  bru.setVar('oauth2_token', token);
}
 
// Can be used for generate a unique name when you need to generate a bunch of entities.
bru.setVar('currentMillis', Date.now());
----

== Logout of Session

Sometimes you might need to login as a different user for testing, the instructions for clearing your sessions are below:

To logout of your session on the Bruno application, go to the collection settings by using the gear icon at the top right of the screen, then click `Auth` to access the authentication settings. At the bottom of the page there is a button to clear the session.

== Headers

Most of the API POST requests require a specific "Content-Type" header. The following headers are setup to be inherited to each request inside of the DINA so they do not need to be setup for each request.

.Common Headers
|===
|Key |Value |Description

|Content-Type
|application/vnd.api+json
|This is only required for POST requests, by default Postman and Insomnia might put `application/json` which will cause an error.

|Crnk-Compact
|true
|Optional. Self and related links can make up to 60% of the response payload size and not always are those links of use. In this case the computation of those links is omitted. Further relationships without data are completely omitted.
|===

== Additional Environments

Only included in the /api-client repo is the local development environment file. Other environment files can be downloaded from the DINA Wiki under the "Bruno Environments" section.
