= Developer Environment Setup

== Prerequisites

The following is required for DINA development:

* Linux operating system (Virtual Machine)
* Visual Studio Code (Install on Linux or see Remote setup below)
* Docker (Install on Linux)

[source, bash]
----
sudo apt install curl 
curl -fsSL https://get.docker.com -o get-docker.sh
sh get-docker.sh
sudo usermod -aG docker ${USER}
----

* Docker Compose (Install on Linux)

[source, bash]
----
DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL https://github.com/docker/compose/releases/download/v2.4.1/docker-compose-linux-x86_64 -o $DOCKER_CONFIG/cli-plugins/docker-compose
chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
----

* Node.js

Install Node Version Manager (NVM): 

[source, bash]
----
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.2/install.sh | bash
----

More info: https://github.com/nvm-sh/nvm#installing-and-updating

Install node 20

[source, bash]
----
nvm install 20
nvm use 20
----

* Yarn

[source, bash]
----
corepack enable
yarn set version 1.22.21
yarn install --frozen-lockfile
----

If you see the following error:

[source, bash]
----
➤ YN0028: │ The lockfile would have been modified by this install, which is explicitly forbidden.
----

Ensure you are using yarn 1.22.21 and node 20:

* Maven

[source, bash]
----
sudo apt install maven
----

* Git

[source, bash]
----
sudo apt install git
----

== Clone Repositories

To get started, you can clone the projects where you are planning to update the code to your home directory:

[source, bash]
----
git clone --branch dev https://github.com/AAFC-BICoE/dina-ui.git
git clone --branch dev https://github.com/AAFC-BICoE/object-store-api.git
git clone --branch dev https://github.com/AAFC-BICoE/seqdb-api.git
git clone --branch dev https://github.com/AAFC-BICoE/agent-api.git
git clone --branch dev https://github.com/AAFC-BICoE/dina-user-api.git
git clone --branch dev https://github.com/AAFC-BICoE/natural-history-collection-api.git
git clone --branch dev https://github.com/AAFC-BICoE/loan-transaction-api.git 
git clone --branch dev https://github.com/AAFC-BICoE/dina-search-api.git 
----

== Visual Studio Code

Visual Studio Code can be installed directly on your Virtual Machine or on your Windows machine using the VSCode Remote instructions below.

=== Recommended Extensions

Once you have VSCode downloaded, you can run this command to install the recommended extensions:

[source, bash]
----
code --install-extension vscjava.vscode-java-pack
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension ms-azuretools.vscode-docker
code --install-extension gabrielbb.vscode-lombok
code --install-extension esbenp.prettier-vscode
code --install-extension dbaeumer.vscode-eslint
code --install-extension firsttris.vscode-jest-runner
code --install-extension alefragnani.project-manager
code --install-extension firefox-devtools.vscode-firefox-debug
----

=== VSCode Remote (Optional)

You can avoid running a slow IDE inside your virtual machine by running VS Code on your host machine instead and connecting to the dev environment using VS Code Remote.

1. Download VSCode for Windows
2. Install the VSCode SSH Remote Extension
+
[source, bash]
----
code --install-extension ms-vscode-remote.remote-ssh
----
+
3. Install Open-SSH Server on your VM
+
[source, bash]
----
sudo apt-get install openssh-server
sudo systemctl enable ssh
sudo systemctl start ssh
----
+
4. Setup Port Forwarding on your VM
+
In order for your Windows VSCode to communicate with your Virtual Machine, you will need to allow for SSH port forwarding.
+
From the `VirtualBox Manager` window, click `Settings`` > `Network` Tab > `Advanced` > `Port Forwarding` > Green `+` icon and add the following rule:
+
.SSH Port Forwarding Rule
|===
|Name |Protocol |Host IP |Host Port |Guest IP |Guest Port

|SSH
|TCP
|Leave Blank
|22
|Leave Blank
|22
|===
+
Click `OK` on both windows to finish setting up the port.
+
5. Configure SSH Remote Extension
+
Once you have the `SSH Remote` extension, using the command palette (CTRL + SHIFT + P) search for `>Remote-SSH: Add New SSH Host...`.
+
In the popup at the top of the screen you can enter the SSH command to connect to your virtual machine (Replacing USERNAME with your Ubuntu username):
+
[source, bash]
----
ssh USERNAME@localhost
----

Now you are connected to your Virtual Machine. You can open projects and use the terminal as if you were in the VM.

More info: https://code.visualstudio.com/docs/remote/remote-overview

=== API Debugging

To debug an API while using the local deployment, you can use the `docker-compose.debug.yml` config which can be enabled from the `start_stop_dina.sh` script.

Once enabled, you will be able to attach your VSCode to an API. The debugging ports can be found in the `.env` file.

Also remember that if you are running VSCode remotely, you will need to port forward the debugging port.

Here is an example of a `launch.json` that can be added to an API for VSCode to attach itself to the java debugger for a specific API:

[source, json]
----
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "java",
      "name": "Attach to Collection API Container",
      "request": "attach",
      "hostName": "localhost",
      "port": "5002"
    }
  ]
}
----

Just ensure that port lines up with the correct API and the port is exposed for VSCode to attach itself.

=== UI Debugging

You will need the `firefox-devtools.vscode-firefox-debug` extension installed in order to debug the UI. This extension allows you to debug the UI using the Firefox browser.

For UI debugging, you will need to use firefox and the `Remote Debugging` feature. The following flags will need to be changed on firefox to enable remote debugging:

1. Open Firefox and type `about:config` in the address bar. Click on "Accept the Risk and Continue".

2. Search and change the following settings:

  `devtools.debugger.remote-enabled` to `true`
  `devtools.chrome.enabled` to `true`
  `devtools.debugger.prompt-connection` to `false`
  `devtools.debugger.remote-port` to `6000`
  `devtools.debugger.force-local` to `false`

3. Close firefox.

4. Open a terminal and run the following command to start firefox with remote debugging enabled:
+
[source, bash]
----
firefox -start-debugger-server
----

5. You will need to add the following to your `launch.json` file in order to attach the debugger to the firefox instance, it can also be found below in the `VSCode Launch Configurations` section:
+
[source, json]
----
{
  "name": "Attach to Firefox",
  "type": "firefox",
  "request": "attach",
  "host": "localhost",
  "port": 6000,
  "webRoot": "${workspaceFolder}/dina-ui",
  "url": "https://dina.local/",
  "pathMappings": [
    {
      "url": "webpack://_n_e/components",
      "path": "${workspaceFolder}/dina-ui/packages/dina-ui/components"
    },
    {
      "url": "webpack://_n_e/common-ui",
      "path": "${workspaceFolder}/dina-ui/packages/common-ui"
    }
  ]
},
----

6. Optional if using remote debugging, you will need to port forward the remote debugging port from your VM to your host machine. This can be done by adding a new port forwarding rule in VirtualBox.
+
.SSH Port Forwarding Rule
|===
|Name |Protocol |Host IP |Host Port |Guest IP |Guest Port
|Firefox Remote Debugging
|TCP
|Leave Blank
|6000
|Leave Blank
|6000
|===
+

Now breakpoints should be able to set in for the DINA UI code and should automatically be hit when the code is executed from the browser.

=== VSCode Launch Configurations

Here is the complete launch configuration for the DINA API projects using the default ports. This can be edited by going to the "Run and debug" tab in VSCode and clicking the gear icon to edit the `launch.json` file.

[source, json]
----
{
  "version": "0.2.0",
  "configurations": [
    {
      "name": "Attach to Firefox",
      "type": "firefox",
      "request": "attach",
      "host": "localhost",
      "port": 6000,
      "webRoot": "${workspaceFolder}/dina-ui",
      "url": "https://dina.local/",
      "pathMappings": [
        {
          "url": "webpack://_n_e/components",
          "path": "${workspaceFolder}/dina-ui/packages/dina-ui/components"
        },
        {
          "url": "webpack://_n_e/common-ui",
          "path": "${workspaceFolder}/dina-ui/packages/common-ui"
        }
      ]
    },
    {
      "type": "java",
      "name": "Attach to Agent API Container",
      "request": "attach",
      "hostName": "localhost",
      "port": "5001"
    },
    {
      "type": "java",
      "name": "Attach to Collection API Container",
      "request": "attach",
      "hostName": "localhost",
      "port": "5002"
    },
    {
      "type": "java",
      "name": "Attach to Loan Transaction API Container",
      "request": "attach",
      "hostName": "localhost",
      "port": "5003"
    },
    {
      "type": "java",
      "name": "Attach to User API Container",
      "request": "attach",
      "hostName": "localhost",
      "port": "5004"
    },
    {
      "type": "java",
      "name": "Attach to Object Store API Container",
      "request": "attach",
      "hostName": "localhost",
      "port": "5005"
    },
    {
      "type": "java",
      "name": "Attach to SeqDB API Container",
      "request": "attach",
      "hostName": "localhost",
      "port": "5006"
    },
    {
      "type": "java",
      "name": "Attach to Export API Container",
      "request": "attach",
      "hostName": "localhost",
      "port": "5007"
    },
    {
      "type": "java",
      "name": "Attach to Search CLI API Container",
      "request": "attach",
      "hostName": "localhost",
      "port": "5008"
    },
    {
      "type": "java",
      "name": "Attach to Search WS API Container",
      "request": "attach",
      "hostName": "localhost",
      "port": "5009"
    }
  ]
}
----
