= JMeter

https://jmeter.apache.org/index.html[Apache JMeter] is used to execute performance/stress test plan.

== Installation

You will need to have java installed on your system. Insure it's installed using:

[source, bash]
----
$ java -version
----

Next, download the latest version of JMeter from the https://jmeter.apache.org/download_jmeter.cgi[JMeter website] and extract it to your desired location:

[source, bash]
----
$ wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.5.zip

$ unzip apache-jmeter-5.5.zip
----

Then you can open up the binary and run jmeter to view the GUI:

[source, bash]
----
$ cd /apache-jmeter-5.5/bin/

$ ./jmeter
----

== How to run

You can start JMeter in GUI mode (default) and open the test plan to visualize it.

To run a test plan from command-line:

[source,bash]
----
$ jmeter -n -t collection_api_module_testplan.jmx -l log.jtl
----

== Module Strucutre

The JMeter test plan is constructed as follows

* Test Plan
** setUp Thread Group 
** Endpoint Thread Groups
** tearDown Thread Group

=== setUp Thread Group

The setUp Thread Group will be executed prior to any regular thread groups, allowing us to setup
access priveleges as well as create any records that may be required by regular thread groups.

Refer to https://jmeter.apache.org/usermanual/component_reference.html#setUp_Thread_Group[setUp Thread Group] component reference

=== Endpoint Thread Group(s)

Each endpoint within the collection-api module will contain a corresponding endpoint thread group.
The thread group will be responsible for setting up and testing the endpoint's CRUD operations.

The layout of each thread group is as follows:

* Endpoint User Defined Variables
** All constant variables will be declared in this configuration element
* HTTP Headers
** Sets the access token and content-type headers, required to perform API requests
* Module Token Controller
** A Module Controller utilized to refresh the access token.
*** https://jmeter.apache.org/usermanual/component_reference.html#Module_Controller[Module Controllers] allow you to perform the actions of other controllers such as using the Token Controller from the setUp Thread Group or the CRUD controllers from other endpoints.
*** All controllers aside from the Module Controllers are https://jmeter.apache.org/usermanual/component_reference.html#Simple_Controller[Simple Controllers] 
    that offer no unique functionality, being used primarily for organizational purposes and to allow Module Controllers to replicate their functionality if needed.
* Create/Update/Delete (CRUD) Endpoint Controllers
** These controllers contain all Controller, Samplers, and Assertions associcated with their respective CRUD operation.
*** Retrieval is tested wtihin each controller when assertions are being made.

=== tearDown Thread Group

The tearDown Thread Group is executed after all of the other thread groups have terminated. This allows
us to remove the records created within the setUp Thread Group without causing any conflicts with the
thread group that user these records.

Refer to https://jmeter.apache.org/usermanual/component_reference.html#tearDown_Thread_Group[tearDown Thread Group] component reference

== CRUD Controllers

The CRUD are the 3 main controllers within each endpoint's thread group, the create, update, and delete controllers.

=== Create Endpoint Controller

This controller will contain all Controllers, Samplers and Assertions that have to do with
the creation of the endpoint recordsws

* Create Basic/Verbose
** Creates a record with the bare minimum fields required and asserts the values match to the variable 
   used in the POST request.
** Creates a record with all fields populated and asserts the values correspond to the variables used in the POST request.
* Invalid Creation(s)
** One or more controllers that attempt to create a record with an invalid request. Some examples of invalid
   creation controllers are creating a record with empty attributes, missing required attributes, or
   having an incorrect 'type' set in the body.
* setUp Controller
** The setUp controller will create relationships entity records for records available through the collection-api.
*** The setUp controller creates these records by utlizing a Module Controller that references the respective
    entities' Endpoint Thread Group's Create Controller.
** In addition to the creation of records, the setUp controller will declaration of random variables
   not only for the designated endpoint, but also any variables required for relationship records.
*** Random variables are utilzied to produce unique variables and prevent unique key conflict errors when increasing thread counts.
   
=== Update Endpoint Controller

* Update Basic/Verbose
** Updates the values of the Basic and Verbose records created prior and asserts that
   all updated values correspond to the ones used in the PATCH request.
* Update Verbose - Empty Body
** Creates a PATCH request on the Verbose entity and asserts that no values have been changed as results of this request.
* Invalid Update(s)
** One or more controllers that attempt to update a record. An example of an invalid update would be attempting
   to update a record that does not exist, such as providing a uuid that does not correspond to any created
   record.
   
=== Delete Endpoint Controller

* Delete Basic/Verbose
** Deletes the records that had been created and asserts that they have been properly removed. Audit records
   may remain.
* Invalid Deletion(s)
** One or more controllers that attempt to remove a record. An example of invalid deletion would be attempting 
   to delete a record that does not exist, such as providing a uuid that does not correspodng to any created
   record.
* tearDown
** The tearDown controller will remove all entities created in the Create Endpoint Controller/setUp Controller.
   The tearDown controller deletes these records by utlizing a Module Controller that references the respective
   entities' Endpoint Thread Group's Delete Controller.

=== Assertions

In all of the CRUD controllers, assertions are being made to ensure that the correct results are produced
by each operation.

** Assertions are managed by using an https://jmeter.apache.org/usermanual/component_reference.html#HTTP_Request[HTTP Request Sampler] 
   to retrieve the designated record and verifying the correctness of the fields. 
*** The majority of assertions are conducted through a Groovy script by means of a https://jmeter.apache.org/usermanual/component_reference.html#JSR223_Assertion[JSR223 Assertion]. 
*** Assertions for Map attributes utilize the https://jmeter.apache.org/usermanual/component_reference.html#JSON_Assertion[JSON Assertion] instead for simpler comparisson.
** In addition to the assertions used to validate data, https://jmeter.apache.org/usermanual/component_reference.html#Response_Assertion[Response Assertions] 
   are used after every HTTP Request Sampler to ensure that the correct response code is also returned.
*** In order to for the Invalid CRUD Controller to return a valid result, a JSR223 Assertion with a Groovy script is used
    in place of the Response Assertion to verify the correct response code has been returned and
    https://jmeter.apache.org/api/org/apache/jmeter/samplers/SampleResult.html#setSuccessful(boolean)[set the successful attribute] of the HTTP Request Sampler to be true.