apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-configmap
data:
{{ (.Files.Glob "config/scripts/skipPostGisExtensions.sh").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm
data:
{{- if .Values.global.environment.isOpenShift }}
  keycloak-realm.json: |-
    {{ .Values.global.environment.config.keycloak.realm_file_content | default "" | nindent 4 }}
{{- else }}
{{ (.Files.Glob "config/keycloak/*").AsConfig | indent 2 }}
{{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-theme
data:
{{ (.Files.Glob "config/theme/*.ftl").AsConfig | indent 2 }}
{{ (.Files.Glob "config/theme/*.properties").AsConfig | indent 2 }}
{{ (.Files.Glob "config/theme/*.css").AsConfig | indent 2 }}
binaryData:
  dina.png: |
    {{ .Files.Get "config/theme/dina-tr-1344-1184.png" | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certs
data:
{{ (.Files.Glob "config/certs/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-settings
data:
{{ (.Files.Glob "config/elastic-configurator/*").AsConfig | indent 2 }}
{{ (.Files.Glob "config/elastic-configurator/agent-index/*").AsConfig | indent 2 }}
{{ (.Files.Glob "config/elastic-configurator/object-store-index/*").AsConfig | indent 2 }}
{{ (.Files.Glob "config/elastic-configurator/collection-index/*").AsConfig | indent 2 }}
{{ (.Files.Glob "config/elastic-configurator/storage-index/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-producer-override-objectstore
data:
  DINA_MESSAGING_ISPRODUCER: {{ .Values.services.objectstoreapi.environment.dina.messaging.isProducer | quote }}
  RABBITMQ_HOST: {{ tpl .Values.services.objectstoreapi.environment.rabbitmq.host . }}
  RABBITMQ_QUEUE: {{ tpl .Values.services.objectstoreapi.environment.rabbitmq.queue . }}
  RABBITMQ_USERNAME: {{ tpl .Values.services.objectstoreapi.environment.rabbitmq.username . }}
  RABBITMQ_PASSWORD: {{ tpl .Values.services.objectstoreapi.environment.rabbitmq.password . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-producer-override-collection
data:
  DINA_MESSAGING_ISPRODUCER: {{ .Values.services.collectionapi.environment.dina.messaging.isProducer | quote }}
  RABBITMQ_HOST: {{ tpl .Values.services.collectionapi.environment.rabbitmq.host . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-producer-override-loantransaction
data:
  DINA_MESSAGING_ISPRODUCER: {{ .Values.services.loantransactionapi.environment.dina.messaging.isProducer | quote }}
  RABBITMQ_HOST: {{ tpl .Values.services.loantransactionapi.environment.rabbitmq.host . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-producer-override-agentapi
data:
  DINA_MESSAGING_ISPRODUCER: {{ .Values.services.agentapi.environment.dina.messaging.isProducer | quote }}
  RABBITMQ_HOST: {{ tpl .Values.services.agentapi.environment.rabbitmq.host . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-producer-override-exportapi
data:
  DINA_MESSAGING_ISCONSUMER: {{ .Values.services.dinaexportapi.environment.dina.messaging.isConsumer | quote }}
  DINA_MESSAGING_EXPORT_QUEUE: {{ tpl .Values.services.dinaexportapi.environment.dina.messaging.export.queue . }}
  DINA_EXPORT_OBJECT_STORE_DOWNLOAD_URL: {{ tpl .Values.services.dinaexportapi.environment.dina.export.objectStoreDownloadUrl . }}
  RABBITMQ_HOST: {{ tpl .Values.services.dinaexportapi.environment.rabbitmq.host . }}
  RABBITMQ_USERNAME: {{ tpl .Values.services.dinaexportapi.environment.rabbitmq.username . }}
  RABBITMQ_PASSWORD: {{ tpl .Values.services.dinaexportapi.environment.rabbitmq.password . }}
  HTTP-CLIENT_OPENID-CONNECT-BASE-URL: {{ tpl .Values.services.dinaexportapi.environment.http_client.openid_connect_base_url . }}
  HTTP-CLIENT_CLIENT-ID: {{ tpl .Values.services.dinaexportapi.environment.http_client.client_id . }}
  HTTP-CLIENT_USERNAME: {{ tpl .Values.services.dinaexportapi.environment.http_client.username . }}
  HTTP-CLIENT_PASSWORD: {{ tpl .Values.services.dinaexportapi.environment.http_client.password . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-welcome
data:
{{ (.Files.Glob "config/ui/welcome-bienvenue.html").AsConfig | indent 2 }}
