apiVersion: v1
kind: ConfigMap
metadata:
  name: scripts-configmap
data:
{{ (.Files.Glob "config/scripts/skipPostGisExtensions.sh").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
data:
{{ (.Files.Glob "config/keycloak/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-theme
data:
{{ (.Files.Glob "config/theme/*.ftl").AsConfig | indent 2 }}
{{ (.Files.Glob "config/theme/*.properties").AsConfig | indent 2 }}
{{ (.Files.Glob "config/theme/*.css").AsConfig | indent 2 }}
binaryData:
  dina.png: |
    {{ .Files.Get "config/theme/dina-tr-1344-1184.png" | b64enc }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: certs
data:
{{ (.Files.Glob "config/certs/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: elastic-settings
data:
{{ (.Files.Glob "config/elastic-configurator/*").AsConfig | indent 2 }}
{{ (.Files.Glob "config/elastic-configurator/agent-index/*").AsConfig | indent 2 }}
{{ (.Files.Glob "config/elastic-configurator/object-store-index/*").AsConfig | indent 2 }}
{{ (.Files.Glob "config/elastic-configurator/collection-index/*").AsConfig | indent 2 }}
{{ (.Files.Glob "config/elastic-configurator/storage-index/*").AsConfig | indent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-producer-override-objectstore
data:
  MESSAGING_ISPRODUCER: {{ .Values.services.objectstoreapi.environment.messaging.isProducer | quote }}
  RABBITMQ_HOST: {{ tpl .Values.services.objectstoreapi.environment.rabbitmq.host . }}
  RABBITMQ_QUEUE: {{ .Values.services.objectstoreapi.environment.rabbitmq.queue }}
  RABBITMQ_EXCHANGE: {{ .Values.services.objectstoreapi.environment.rabbitmq.exchange }}
  RABBITMQ_ROUTINGKEY: {{ .Values.services.objectstoreapi.environment.rabbitmq.routingkey }}
  RABBITMQ_USERNAME: {{ .Values.services.objectstoreapi.environment.rabbitmq.username }}
  RABBITMQ_PASSWORD: {{ .Values.services.objectstoreapi.environment.rabbitmq.password }}
  RABBITMQ_PORT: {{ .Values.services.objectstoreapi.environment.rabbitmq.port | quote }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-producer-override-collection
data:
  MESSAGING_ISPRODUCER: {{ .Values.services.collectionapi.environment.messaging.isProducer | quote }}
  RABBITMQ_HOST: {{ tpl .Values.services.collectionapi.environment.rabbitmq.host . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-producer-override-loantransaction
data:
  MESSAGING_ISPRODUCER: {{ .Values.services.loantransactionapi.environment.messaging.isProducer | quote }}
  RABBITMQ_HOST: {{ tpl .Values.services.loantransactionapi.environment.rabbitmq.host . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: message-producer-override-agentapi
data:
  MESSAGING_ISPRODUCER: {{ .Values.services.agentapi.environment.messaging.isProducer | quote }}
  RABBITMQ_HOST: {{ tpl .Values.services.agentapi.environment.rabbitmq.host . }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: report-label
data:
{{ (.Files.Glob "config/report-label/templates/*").AsConfig | indent 2 }}