apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/keycloak-data/"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-db-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi