version: "3.9"

services:
  agent-api:
    environment:
      dina.messaging.isProducer: "true"
      rabbitmq.host: rabbitmq-dina
    networks:
      - dina_rabbitmq_net

  collection-api:
    environment:
      dina.messaging.isProducer: "true"
      rabbitmq.host: rabbitmq-dina
    networks:
      - dina_rabbitmq_net

  loan-transaction-api:
    environment:
      dina.messaging.isProducer: "true"
      rabbitmq.host: rabbitmq-dina
    networks:
      - dina_rabbitmq_net

  object-store-api:
    environment:
      dina.messaging.isProducer: "true"
      rabbitmq.host: rabbitmq-dina
      rabbitmq.queue: dina.search.queue
      rabbitmq.username: guest
      rabbitmq.password: guest
    networks:
      - dina_rabbitmq_net
      
  dina-export-api:
    environment:
      dina.messaging.isConsumer: "true"
      dina.messaging.export.queue: dina.export.queue
      dina.export.objectStoreDownloadUrl: http://object-store-api:8080/api/v1/toa
      rabbitmq.host: rabbitmq-dina
      rabbitmq.username: guest
      rabbitmq.password: guest
      http-client.openid-connect-base-url: ${KEYCLOAK_INTERNAL_URL}/realms/dina/protocol/openid-connect/
      http-client.client-id: dina-public
      http-client.username: cnc-su
      http-client.password: cnc-su

    networks:
      - dina_rabbitmq_net
      
