version: "3.9"

services:
  agent-api:
    environment:
      messaging.isProducer: "true"
      rabbitmq.host: rabbitmq-dina
    networks:
      - dina_rabbitmq_net

  collection-api:
    environment:
      messaging.isProducer: "true"
      rabbitmq.host: rabbitmq-dina
    networks:
      - dina_rabbitmq_net

  loan-transaction-api:
    environment:
      messaging.isProducer: "true"
      rabbitmq.host: rabbitmq-dina
    networks:
      - dina_rabbitmq_net

  object-store-api:
    environment:
      dina.messaging.isProducer: "true"
      rabbitmq.host: rabbitmq-dina
      rabbitmq.queue: dina.search.queue
      rabbitmq.username: guest
      rabbitmq.password: guest
    networks:
      - dina_rabbitmq_net
